### ISSUE TITLE
Train error : index out of bound in dataset.py 

### ISSUE THREAD

**Issue by jenapss** [pythonlessons/TensorFlow-2.x-YOLOv3#10]
epoch: 0 step:   97/100, lr:0.000048, giou_loss:   7.67, conf_loss: 199.07, prob_loss:   9.08, total_loss: 215.82
epoch: 0 step:   98/100, lr:0.000049, giou_loss:   9.68, conf_loss: 200.08, prob_loss:  10.70, total_loss: 220.46
epoch: 0 step:   99/100, lr:0.000049, giou_loss:   6.33, conf_loss: 201.52, prob_loss:   8.38, total_loss: 216.23
epoch: 0 step:    0/100, lr:0.000050, giou_loss:   8.88, conf_loss: 196.33, prob_loss:  14.15, total_loss: 219.36
epoch: 0 step:    1/100, lr:0.000050, giou_loss:   8.39, conf_loss: 193.57, prob_loss:   9.26, total_loss: 211.23
Traceback (most recent call last):
  File "train.py", line 173, in <module>
    main()
  File "train.py", line 145, in main
    for image_data, target in testset:
  File "/Users/jelaleddin/TensorFlow-2.x-YOLOv3/yolov3/dataset.py", line 97, in __next__
    label_sbbox, label_mbbox, label_lbbox, sbboxes, mbboxes, lbboxes = self.preprocess_true_boxes(bboxes)
  File "/Users/jelaleddin/TensorFlow-2.x-YOLOv3/yolov3/dataset.py", line 220, in preprocess_true_boxes
    label[i][yind, xind, iou_mask, :] = 0
IndexError: index 13 is out of bounds for axis 1 with size 13

**I am getting this error, what can be the reason of such problem?Please write a comment if you have faced same issue**

**Comment by pythonlessons** [comment]
Because the problem comes after first epoch where test dataset validation starts, There should be something wrong with your test dataset

**Comment by jenapss** [comment]
what it could be? I have run that code for multiple times I have the same issue



**epoch: 0 step:   86/200, lr:0.000022, giou_loss:   4.20, conf_loss: 299.90, prob_loss:   7.99, total_loss: 312.09
epoch: 0 step:   87/200, lr:0.000022, giou_loss:   3.12, conf_loss: 298.58, prob_loss:   5.02, total_loss: 306.72
epoch: 0 step:   88/200, lr:0.000022, giou_loss:   3.38, conf_loss: 296.69, prob_loss:   4.97, total_loss: 305.04
Traceback (most recent call last):
  File "/Users/jelaleddin/TensorFlow-2.x-YOLOv3/train.py", line 180, in <module>
    main()
  File "/Users/jelaleddin/TensorFlow-2.x-YOLOv3/train.py", line 140, in main
    for image_data, target in trainset:
  File "/Users/jelaleddin/TensorFlow-2.x-YOLOv3/yolov3/dataset.py", line 97, in __next__
    label_sbbox, label_mbbox, label_lbbox, sbboxes, mbboxes, lbboxes = self.preprocess_true_boxes(bboxes)
  File "/Users/jelaleddin/TensorFlow-2.x-YOLOv3/yolov3/dataset.py", line 220, in preprocess_true_boxes
    label[i][yind, xind, iou_mask, :] = 0
IndexError: index 13 is out of bounds for axis 1 with size 13

Process finished with exit code 1**

**Comment by jenapss** [comment]
![IMG_5081](https://user-images.githubusercontent.com/43576850/85929761-cc637580-b8d0-11ea-8b47-0baa4e3eba3b.jpg)
this is image from my test dataset, I dont know whats wrong with images, I used labelImg for annotating them.

**Comment by jenapss** [comment]
Please can you help me find some workaround for this issue? What else I should share with you(maybe code parts or annotation XML files?) so you could understand where is problem?

**Comment by pythonlessons** [comment]
Can you give me link to download your labeled dataset?

**Comment by tomkisiela** [comment]
Hello, I've got the same problem when I try to train with the tiny weights. @jenapss Did you manage to solve your problem ?

**Comment by pythonlessons** [comment]
> Hello, I've got the same problem when I try to train with the tiny weights. @jenapss Did you manage to solve your problem ?

No, I didn't receive a dataset to reproduce the error. Noone sent it to me yet.

**Comment by tomkisiela** [comment]
https://drive.google.com/drive/folders/1say3a5hF8Qy1hEFTAJpWSnD-IjyTN0RH?usp=sharing here is a link to my dataset if you can have a look  I'm trying to detect Car Truck Bus Person Trafic sign and Trafic Light. But it's quite huge

**Comment by pythonlessons** [comment]
It's 2GB, not a problem. Right now I am working on mAP measuring, after that, I'll check your dataset.

**Comment by jenapss** [comment]
@tomkisiela hello my friend,  I havent solved the problem yet, I am uploading my image dataset (3GB) to my Google drive,to show you, will share as soon as it finishes, thank you.
how about you? have you solved this issue?

**Comment by tomkisiela** [comment]
Hello, I think that @pythonlessons was right, when I added more images in my dataset and run XML_to_yolo, something went wrong. I got back to an older version and it seems to work better know.
 @pythonlessons I think you don't need to check my dataset but ty for your reactivity :)

**Comment by jenapss** [comment]
I had the same situation. I trained first on my initial first dataset collected with google images , it was working fine, but when I collected images on my own with smartphone and annotated them, I then trained tiny-Yolo on this second dataset, I started getting those errors described above on the top of conversation. Did you find out the reason of that issue? Please can you share with me? Thank you!

**Comment by pythonlessons** [comment]
> I had the same situation. I trained first on my initial first dataset collected with google images , it was working fine, but when I collected images on my own with smartphone and annotated them, I then trained tiny-Yolo on this second dataset, I started getting those errors described above on the top of conversation. Did you find out the reason of that issue? Please can you share with me? Thank you!

Can you send me a link to download your dataset, I'll try to find a reason

**Comment by jenapss** [comment]
https://drive.google.com/drive/folders/1jVd2dBetcN8ieNsgW2n6yJf770k1k6IP?usp=sharing

here is my link to my dataset

**Comment by jenapss** [comment]
any news🙏🏻🙏🏻😁?

**Comment by pythonlessons** [comment]
> any news🙏🏻🙏🏻😁?

Yes, just checked your dataset.
it' something wrong with test/IMG_5408.jpg
but, I can't understand what is wrong there, so I added an exception to skip images with such errors

try to download new dataset.py file and try again

**Comment by jenapss** [comment]
**I just checked the script, it keeps throwing another error:**
epoch: 0 step:  199/200, lr:0.000050, giou_loss:   4.59, conf_loss: 141.40, prob_loss:   5.57, total_loss: 151.56
epoch: 0 step:    0/200, lr:0.000050, giou_loss:   2.97, conf_loss: 143.36, prob_loss:   6.14, total_loss: 152.46
epoch: 0 step:    1/200, lr:0.000050, giou_loss:   6.69, conf_loss: 141.34, prob_loss:   7.31, total_loss: 155.34
IndexError, something wrong with /Users/jelaleddin/TensorFlow-2.x-YOLOv3/custom_dataset/test_output/IMG_5426.jpg remove this image, annotation file, run XML_to_YOLOv3.py and continue
IndexError, something wrong with /Users/jelaleddin/TensorFlow-2.x-YOLOv3/custom_dataset/test_output/IMG_5777.jpg remove this image, annotation file, run XML_to_YOLOv3.py and continue
IndexError, something wrong with /Users/jelaleddin/TensorFlow-2.x-YOLOv3/custom_dataset/test_output/IMG_5094.jpg remove this image, annotation file, run XML_to_YOLOv3.py and continue
Traceback (most recent call last):
  File "train.py", line 180, in <module>
    main()
  File "train.py", line 152, in main
    for image_data, target in testset:
  File "/Users/jelaleddin/TensorFlow-2.x-YOLOv3/yolov3/dataset.py", line 104, in __next__
    batch_label_sbbox[num, :, :, :, :] = label_sbbox
UnboundLocalError: local variable 'label_sbbox' referenced before assignment

**Comment by jenapss** [comment]
Have you tried to run the new version of dataset.py file on your own? Did it work for you?

**Comment by pythonlessons** [comment]
> Have you tried to run the new version of dataset.py file on your own? Did it work for you?

Yes I tried,
Take a look at these lines:
```
IndexError, something wrong with /Users/jelaleddin/TensorFlow-2.x-YOLOv3/custom_dataset/test_output/IMG_5426.jpg remove this image, annotation file, run XML_to_YOLOv3.py and continue
IndexError, something wrong with /Users/jelaleddin/TensorFlow-2.x-YOLOv3/custom_dataset/test_output/IMG_5777.jpg remove this image, annotation file, run XML_to_YOLOv3.py and continue
IndexError, something wrong with /Users/jelaleddin/TensorFlow-2.x-YOLOv3/custom_dataset/test_output/IMG_5094.jpg remove this image, annotation file, run XML_to_YOLOv3.py and continue
```
I couldn't find out what is wrong with these images and labels, but problem should be solved if you remove these

**Comment by jenapss** [comment]
got it, thank you so much🙏🏻, for now it started training:)

**Comment by pythonlessons** [comment]
> got it, thank you so much🙏🏻, I deleted those images & annotations from dataset, for now it started training:)

Without you, I couldn't find this strange issue, so thank you for your help!
Now others also won't get this error because of your help

**Comment by jenapss** [comment]
🙏🏻
