### ISSUE TITLE
Yolo V3-tiny (or Yolo V3-tiny) Train on Google Colab

### ISSUE THREAD

**Issue by chrisTopp84** [pythonlessons/TensorFlow-2.x-YOLOv3#100]
Hi @pythonlessons 

this is rather a question than a problem.
First thanks for this tutorial -> https://pylessons.com/YOLOv3-TF2-GoogleColab/

I wonder if it is possible not to train Yolo V3/V4 but Yolo V3-Tiny / V4-Tiny on GoogleColab?
If it is possible what do I have to change within this tutorial https://pylessons.com/YOLOv3-TF2-GoogleColab/

Thanks in advance and best regards
chris

**Comment by pythonlessons** [comment]
Yes, you can train tiny, change configs.py file
