### ISSUE TITLE
inference/tensorrt

### ISSUE THREAD

**Issue by chillum1718** [pythonlessons/TensorFlow-2.x-YOLOv3#101]
how can we check inference on multiple images

**Comment by pythonlessons** [comment]
I didn't try this by myself, you should try it by yourself.

**Comment by chillum1718** [comment]
Can we connect for further discussion?

**Comment by pythonlessons** [comment]
> Can we connect for further discussion?

Actually right now I don't have time to come back to this project in the near future, to test this

**Comment by chillum1718** [comment]
Yes, sure.
