### ISSUE TITLE
How to get BBOX and CLASSNAME values instead of drawing over the image. 

### ISSUE THREAD

**Issue by PonraJS-21** [pythonlessons/TensorFlow-2.x-YOLOv3#103]
I would like to know the syntax for getting BBOX and it's CLASSNAME from prediction without drawing Over it?. Is that possible, or should I do it myself?

**Comment by pythonlessons** [comment]
Go to a specific function, where the BBOX drawing is done, then just print it or return it, do whatever you want.

**Comment by PonraJS-21** [comment]
Okay ✌️
