### ISSUE TITLE
Error during training on custom dataset

### ISSUE THREAD

**Issue by b0ssplz** [pythonlessons/TensorFlow-2.x-YOLOv3#106]
Hello, I was following tutorial for training YoloV3 on custom dataset, everything went smoothly with the training and loss, but at the end this error was shown:

```
epoch:99 step:    0/21, lr:0.000001, giou_loss:   0.42, conf_loss:   0.91, prob_loss:   0.14, total_loss:   1.47
epoch:99 step:    1/21, lr:0.000001, giou_loss:   0.38, conf_loss:   0.82, prob_loss:   0.11, total_loss:   1.31
configure TEST options to validate model
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    main()
  File "train.py", line 180, in main
    mAP_model.load_weights(save_directory) # use keras weights
UnboundLocalError: local variable 'save_directory' referenced before assignment
```
It seems to me that variable save_directory is not assigned in validate_step function in train.py. There are those 3 ifs that assign path to this variable but I guess that any of these if statements passed.

I've changed variables in config.py: TRAIN_CLASSES, TRAIN_ANNOT_PATH and TEST_ANNOT_PATH so they show the good path to files.
Oh, and I also work on yolov3-tiny.weights.

I've bruteforced my way by hardcoding the path and now I get this error:

```
  File "C:\Users\b0ss\Desktop\TensorFlow-2.x-YOLOv3-master\evaluate_mAP.py", line 169, in get_mAP
    ms = sum(times)/len(times)*1000
ZeroDivisionError: division by zero
```

How to solve it?
Also could you explain if file "yolov3_custom_Tiny.data-00000-of-00001" created in checkpoints folder is the end-result of training? How do I set it in configs.py?

EDIT:
I decided to repeat everything the same way as in license-plate tutorial (except for yolo-tiny weights) and training went okay, but when I run detection_custom.py with a path to selected image (I even downloaded the same GOD 666 license plate image) the following error occurs:

```
Traceback (most recent call last):
  File "C:/Users/b0ss/Desktop/clean tf yolo/detection_custom.py", line 23, in <module>
    detect_image(yolo, image_path, "./IMAGES/5xsa.jpg", input_size=YOLO_INPUT_SIZE, show=True, CLASSES=TRAIN_CLASSES, rectangle_colors=(255,0,0))
  File "C:\Users\b0ss\Desktop\clean tf yolo\yolov3\utils.py", line 296, in detect_image
    image = draw_bbox(original_image, bboxes, CLASSES=CLASSES, rectangle_colors=rectangle_colors)
  File "C:\Users\b0ss\Desktop\clean tf yolo\yolov3\utils.py", line 157, in draw_bbox
    label = "{}".format(NUM_CLASS[class_ind]) + score_str
KeyError: 2

Process finished with exit code 1
```
EDIT2:
I decided to ignore this error by putting draw_bbox function in try-except code. After that predicted image has shown but it doesn't detect license-plates.
It looks like this: [https://imgur.com/EYyV51Q](https://imgur.com/EYyV51Q)
So it detects default classes but rewrites class names to license-plate? Why does it happen?
I've also discovered that in labelimg something is wrong with these downloaded Romanian (European Union) Dataset of License Plates. Labelimg doesn't detect rectangles when I browse through these photos. Only my own custom ones which I created manually seem to work. I experimented and found out that it's because of this code:
```
			<xmin>768.6884724356514</xmin>
			<ymin>396.83605506771886</ymin>
			<xmax>869.3968497887056</xmax>
			<ymax>420.983606557377</ymax>
```
When I crop out the values to:
```
			<xmin>768</xmin>
			<ymin>396</ymin>
			<xmax>869</xmax>
			<ymax>420</ymax>
Labelimg then sees the rectangle. So is it because of this that training failed? 
```

**Comment by pythonlessons** [comment]
Hi,
That's a nice experiment you did.
And yes, I think these float numbers fault is why training failed, probably you need to write some kind of script to change 
```
<xmin>768.6884724356514</xmin>
<ymin>396.83605506771886</ymin>
<xmax>869.3968497887056</xmax>
<ymax>420.983606557377</ymax>
```
 values to integers

**Comment by b0ssplz** [comment]
But aren't they the same in your .xml files in tutorial?
And besides, I think this is the problem only for labelimg since XML_to_YOLOv3.py script transformes these xml files to yolov3 .txt and in this ____train.txt there are coordinates but the float part is cut already.
So right now I don't really think that's the case. 
I'm still trying to debug it but I'm losing that hope that I can do this.
Do you have other ideas? It's really weird that following your license-plate tutorial is not giving the same results (actually any).
Like I said before, I think it still relates to old weights or something because the objects it detected are from default weights (people, cars) and not license-plate like it's supposed to.

**Comment by pythonlessons** [comment]
Updated Utils.py, download the new one and try again
