### ISSUE TITLE
CUDNN_STATUS_ALLOC_FAILED

### ISSUE THREAD

**Issue by proxytype** [pythonlessons/TensorFlow-2.x-YOLOv3#107]
add this line in case of allocation error by python itself
os.environ['TF_FORCE_GPU_ALLOW_GROWTH'] = 'true'

cause me a lot of problems

**Comment by pythonlessons** [comment]
Hi, sure, will add this to train.py

**Comment by proxytype** [comment]
Excellent! Thanks
