### ISSUE TITLE
KEY ERROR during testing

### ISSUE THREAD

**Issue by PNiharika22** [pythonlessons/TensorFlow-2.x-YOLOv3#108]
KeyError                                  Traceback (most recent call last)
<ipython-input-2-961cc6631565> in <module>
     11 
     12 yolo = Load_Yolo_model()
---> 13 detect_image(yolo, image_path, "./IMAGES/detect.jpg", input_size=YOLO_INPUT_SIZE, show=True, CLASSES=TRAIN_CLASSES, rectangle_colors=(255,0,0))
     14 detect_video(yolo, video_path, './IMAGES/detected3.mp4', input_size=YOLO_INPUT_SIZE, show=False, CLASSES=TRAIN_CLASSES, rectangle_colors=(255,0,0))
     15 detect_realtime(yolo, '', input_size=YOLO_INPUT_SIZE, show=True, CLASSES=TRAIN_CLASSES, rectangle_colors=(255, 0, 0))

~\New folder\TensorFlow-2.x-YOLOv3-master\TensorFlow-2.x-YOLOv3-master\yolov3\utils.py in detect_image(Yolo, image_path, output_path, input_size, show, CLASSES, score_threshold, iou_threshold, rectangle_colors)
    294     bboxes = nms(bboxes, iou_threshold, method='nms')
    295 
--> 296     image = draw_bbox(original_image, bboxes, CLASSES=CLASSES, rectangle_colors=rectangle_colors)
    297     # CreateXMLfile("XML_Detections", str(int(time.time())), original_image, bboxes, read_class_names(CLASSES))
    298 

~\New folder\TensorFlow-2.x-YOLOv3-master\TensorFlow-2.x-YOLOv3-master\yolov3\utils.py in draw_bbox(image, bboxes, CLASSES, show_label, show_confidence, Text_colors, rectangle_colors, tracking)
    155             if tracking: score_str = " "+str(score)
    156 
--> 157             label = "{}".format(NUM_CLASS[class_ind]) + score_str
    158 
    159             # get text size

KeyError: 3

I'm facing key error 1 and 3 while testing.
I tried fixing it but it was of no use.
can you please suggest me how to solve this.

**Comment by kalai2033** [comment]
@PNiharika22 I am also facing the same issue

**Comment by pythonlessons** [comment]
Can you copy your configs.py file?

**Comment by kalai2033** [comment]
Please find the attached configs.py

**Comment by SamTulster** [comment]
I'm having a similar error when running detection_custom for license plate data on yolov3:

`Traceback (most recent call last):
  File "detection_custom.py", line 23, in <module>
    detect_image(yolo, image_path, "IMAGES/plate1_detect.jpg", input_size=YOLO_INPUT_SIZE, show=True, CLASSES=TRAIN_CLASSES, rectangle_colors=(255,0,0))
  File "C:\Users\user\Desktop\TensorFlow-2.x-YOLOv3-master\yolov3\utils.py", line 296, in detect_image
    image = draw_bbox(original_image, bboxes, CLASSES=CLASSES, rectangle_colors=rectangle_colors)
  File "C:\Users\samtu\Desktop\4995-004-DL-CV\TensorFlow-2.x-YOLOv3-master\yolov3\utils.py", line 157, in draw_bbox
    label = "{}".format(NUM_CLASS[class_ind]) + score_str
KeyError: 2`

**Comment by SamTulster** [comment]
I'm having a similar error when running detection_custom for license plate data on yolov3:

`Traceback (most recent call last): File "detection_custom.py", line 23, in <module> detect_image(yolo, image_path, "IMAGES/plate1_detect.jpg", input_size=YOLO_INPUT_SIZE, show=True, CLASSES=TRAIN_CLASSES, rectangle_colors=(255,0,0)) File "C:\Users\user\Desktop\TensorFlow-2.x-YOLOv3-master\yolov3\utils.py", line 296, in detect_image image = draw_bbox(original_image, bboxes, CLASSES=CLASSES, rectangle_colors=rectangle_colors) File "C:\Users\user\Desktop\TensorFlow-2.x-YOLOv3-master\yolov3\utils.py", line 157, in draw_bbox label = "{}".format(NUM_CLASS[class_ind]) + score_str KeyError: 2`

**Comment by pythonlessons** [comment]
Could someone compress your files to zip, and add them to google drive, so I could download and test it out, this would be easier for me to find an issue

**Comment by SamTulster** [comment]
> Could someone of you compress your files to zip, and add them to google drive, so I could download and test it out, this would be easier for me to find an issue

I found my problem! I was following your text tutorial, and it seems that it was loading the original yolov3 weights. I modified `detection_custom.py` like in your video, and it runs without error. However, it seems that it does not have Non-Maximum Suppression.

Here is my `detection_custom.py`. Can you let me know what I did wrong?

`import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
import cv2
import numpy as np
import tensorflow as tf
from yolov3.yolov3 import Create_Yolov3
from yolov3.utils import detect_image, detect_realtime, detect_video, Load_Yolo_model, detect_video_realtime_mp
from yolov3.configs import *

image_path   = "./IMAGES/plate_1.jpg"
video_path   = "./IMAGES/test.mp4"

#yolo = Load_Yolo_model()

yolo = Create_Yolov3(input_size=YOLO_INPUT_SIZE, CLASSES=TRAIN_CLASSES)
yolo.load_weights("./checkpoints/yolov3_custom")

detect_image(yolo, image_path, "./IMAGES/plate_1_detect.jpg", input_size=YOLO_INPUT_SIZE, show=True, CLASSES=TRAIN_CLASSES, rectangle_colors=(255,0,0))`

**Comment by pythonlessons** [comment]
It should work as it is, best would be to get someone's files to reproduce error. I do not recommend to use `from yolov3.yolov3 import Create_Yolov3`

**Comment by SamTulster** [comment]
> It should work as it is, best would be to get someone's files to reproduce error. I do not recommend to use `from yolov3.yolov3 import Create_Yolov3`

Certainly! Here's the [Google Drive link](https://drive.google.com/file/d/12c18MvFmyX-u7yVW9Z8AeYQY8gfXPklq/view?usp=sharing).

Running python detection_custom.py will result in KeyError 2. Modifying it like above (or un-commenting the lines in that file) will produce desired result.

**Comment by pythonlessons** [comment]
> > It should work as it is, best would be to get someone's files to reproduce error. I do not recommend to use `from yolov3.yolov3 import Create_Yolov3`
> 
> Certainly! Here's the [Google Drive link](https://drive.google.com/file/d/12c18MvFmyX-u7yVW9Z8AeYQY8gfXPklq/view?usp=sharing).
> 
> Running `python detection_custom.py` will result in KeyError 2. Modifying it like above (or un-commenting the lines in that file) will produce desired result.

Thanks for your files, updated utils.py file with some updates, you can download utils.py and try again, you will find whats wrong

**Comment by SamTulster** [comment]
> > > It should work as it is, best would be to get someone's files to reproduce error. I do not recommend to use `from yolov3.yolov3 import Create_Yolov3`
> > 
> > 
> > Certainly! Here's the [Google Drive link](https://drive.google.com/file/d/12c18MvFmyX-u7yVW9Z8AeYQY8gfXPklq/view?usp=sharing).
> > Running `python detection_custom.py` will result in KeyError 2. Modifying it like above (or un-commenting the lines in that file) will produce desired result.
> 
> Thanks for your files, updated utils.py file with some updates, you can download utils.py and try again, you will find whats wrong

Thanks! I downloaded your updated repo, and copied the new utils.py file to replace my old utils.py.

However, I encounter this error:

```
Traceback (most recent call last):
  File "detection_custom.py", line 29, in <module>
    detect_image(yolo, image_path, "./IMAGES/plate_1_detect.jpg", input_size=YOLO_INPUT_SIZE, show=True, CLASSES=TRAIN_CLASSES, rectangle_colors=(255,0,0))
  File "C:\Users\user\Desktop\TensorFlow-2.x-YOLOv3-master\yolov3\utils.py", line 302, in detect_image
    image = draw_bbox(original_image, bboxes, CLASSES=CLASSES, rectangle_colors=rectangle_colors)
  File "C:\Users\user\Desktop\TensorFlow-2.x-YOLOv3-master\yolov3\utils.py", line 166, in draw_bbox
    (text_width, text_height), baseline = cv2.getTextSize(label, cv2.FONT_HERSHEY_COMPLEX_SMALL,
UnboundLocalError: local variable 'label' referenced before assignment
```

**Comment by pythonlessons** [comment]
You should receive following:
```
Loading Darknet_weights from: model_data/yolov3.weights
You received KeyError, this might be that you are trying to use yolo original weights
while using custom classes, if using custom model in configs.py set YOLO_CUSTOM_WEIGHTS = True
Traceback (most recent call last):
  File "/home/pyrokas/Downloads/yolov3_tf2_KeyError_2/detection_custom.py", line 29, in <module>
    detect_image(yolo, image_path, "./IMAGES/plate_1_detect.jpg", input_size=YOLO_INPUT_SIZE, show=True, CLASSES=TRAIN_CLASSES, rectangle_colors=(255,0,0))
  File "/home/pyrokas/Downloads/yolov3_tf2_KeyError_2/yolov3/utils.py", line 303, in detect_image
    image = draw_bbox(original_image, bboxes, CLASSES=CLASSES, rectangle_colors=rectangle_colors)
  File "/home/pyrokas/Downloads/yolov3_tf2_KeyError_2/yolov3/utils.py", line 167, in draw_bbox
    (text_width, text_height), baseline = cv2.getTextSize(label, cv2.FONT_HERSHEY_COMPLEX_SMALL,
UnboundLocalError: local variable 'label' referenced before assignment
>>> 
```
Before error, you should see the following print:
_**Loading Darknet_weights from: model_data/yolov3.weights
You received KeyError, this might be that you are trying to use yolo original weights
while using custom classes, if using custom model in configs.py set YOLO_CUSTOM_WEIGHTS = True**_

**Comment by SamTulster** [comment]
> You should receive following:
> 
> ```
> Loading Darknet_weights from: model_data/yolov3.weights
> You received KeyError, this might be that you are trying to use yolo original weights
> while using custom classes, if using custom model in configs.py set YOLO_CUSTOM_WEIGHTS = True
> Traceback (most recent call last):
>   File "/home/pyrokas/Downloads/yolov3_tf2_KeyError_2/detection_custom.py", line 29, in <module>
>     detect_image(yolo, image_path, "./IMAGES/plate_1_detect.jpg", input_size=YOLO_INPUT_SIZE, show=True, CLASSES=TRAIN_CLASSES, rectangle_colors=(255,0,0))
>   File "/home/pyrokas/Downloads/yolov3_tf2_KeyError_2/yolov3/utils.py", line 303, in detect_image
>     image = draw_bbox(original_image, bboxes, CLASSES=CLASSES, rectangle_colors=rectangle_colors)
>   File "/home/pyrokas/Downloads/yolov3_tf2_KeyError_2/yolov3/utils.py", line 167, in draw_bbox
>     (text_width, text_height), baseline = cv2.getTextSize(label, cv2.FONT_HERSHEY_COMPLEX_SMALL,
> UnboundLocalError: local variable 'label' referenced before assignment
> >>> 
> ```
> 
> Before error, you should see the following print:
> _**Loading Darknet_weights from: model_data/yolov3.weights You received KeyError, this might be that you are trying to use yolo original weights while using custom classes, if using custom model in configs.py set YOLO_CUSTOM_WEIGHTS = True**_

Thank you so much! I think that's where my problem was coming from!

**Comment by pythonlessons** [comment]
Ok, cool, I can close this now
