### ISSUE TITLE
How to disable Queue?

### ISSUE THREAD

**Issue by Tylersuard** [pythonlessons/TensorFlow-2.x-YOLOv3#111]
Hello!  Thank you for posting your tutorial.  It was easy and fast, and I got it working immediately.
My problem is, Yolov3 takes about 5 seconds to process each image, and openCV captures images more quickly than that.
As a result, it takes about 30 seconds for the on-screen image to update, because Yolo has to run through all the images in the Queue.  Is there any way to disable the queue, and just have openCV wait until the last image is done being predicted on before taking a new picture?

**Comment by pythonlessons** [comment]
What function you use actually? There are no queues in this tutorial

**Comment by Tylersuard** [comment]
You're right, that was my mistake. I looked at the code again.
My problem is, I am running the full Yolov3 model on the Raspberry Pi 4. I can't run Yolov3tiny because it is too inaccurate. I am ok with the 1 frame every 5 seconds inference time, but the problem is it takes 30 seconds to update. For instance, the program is performing inference at one frame every five seconds, but when I put my hand in front of the camera, it takes 30 seconds before the pi's screen shows the change, because it still has 6 frames to go through. Is there any way to reduce that delay time to the actual 5 seconds processing time instead of 30 seconds?
Thank you for your help.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
