### ISSUE TITLE
New tensorflow 2.4.0

### ISSUE THREAD

**Issue by hernancontigiani** [pythonlessons/TensorFlow-2.x-YOLOv3#112]
Hi!
I have been using this repo for detection for a while. First of all thanks a lot to take the time to implement in tensorflow :+1: 
With new tensorflow 2.4.0 is seems that yolo stop detection anything, I have downgrade colab to tensorflow 2.3.X and everything goes back well again.
Regards, Hernan

**Comment by pythonlessons** [comment]
Thanks, don't have time to debug why it doesn't work with 2.4.0, but thanks! But I'll add a note
