### ISSUE TITLE
UnboundLocalError: local variable 'save_directory' referenced before assignment

### ISSUE THREAD

**Issue by zaheerbeg21** [pythonlessons/TensorFlow-2.x-YOLOv3#119]
in classes.names or names.txt is it ok if i specify class names as "number plate" instead of number-plate , My classes as 
'sub main distribution board' , i did not changes just changes in config
'distribution board'   and so on showing error  - > Traceback (most recent call last):
  File "train.py", line 185, in <module>
    main()
  File "train.py", line 181, in main
    mAP_model.load_weights(save_directory) # use keras weights
UnboundLocalError: local variable 'save_directory' referenced before assignment

**Comment by pythonlessons** [comment]
You don't have saved model weights to measure mAP, check TRAIN_SAVE_BEST_ONLY and TRAIN_SAVE_CHECKPOINT lines in configs.py
