### ISSUE TITLE
Error while running inference on CPU windows 10  

### ISSUE THREAD

**Issue by manishs86** [pythonlessons/TensorFlow-2.x-YOLOv3#14]
(tf2) PS D:\TF2_YOLOv3\TensorFlow-2.x-YOLOv3-master> python detection_demo.py                                                                                           2020-07-01 00:12:42.907737: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "detection_demo.py", line 29, in <module>
    load_yolo_weights(yolo, Darknet_weights) # use Darknet weights
  File "D:\TF2_YOLOv3\TensorFlow-2.x-YOLOv3-master\yolov3\utils.py", line 59, in load_yolo_weights
    conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0])
ValueError: cannot reshape array of size 55195 into shape (128,64,3,3)

**Comment by pythonlessons** [comment]
what tf version you use, how I could reproduce this error?

**Comment by Deep-learning999** [comment]
weights
  File "/aTensorFlow2/yolov3/utils.py", line 59, in load_yolo_weights
    conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0])
ValueError: cannot reshape array of size 82254 into shape (256,512,1,1)

**Comment by pythonlessons** [comment]
> weights
> File "/aTensorFlow2/yolov3/utils.py", line 59, in load_yolo_weights
> conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0])
> ValueError: cannot reshape array of size 82254 into shape (256,512,1,1)

How I can reproduce your error?
