### ISSUE TITLE
ciou_loss

### ISSUE THREAD

**Issue by lihualilee** [pythonlessons/TensorFlow-2.x-YOLOv3#144]
when i use ciou_loss，the loss number always is nan?
![image](https://user-images.githubusercontent.com/64268860/114334870-137bd800-9b7e-11eb-9479-43bf79c2cc18.png)
about ar_gt = boxes2[..., 2] / boxes2[..., 3]，We're using division, but we're going to have a lot of zeros in the denominator

**Comment by pythonlessons** [comment]
Yes, ciou is not working

**Comment by WillLiGitHub** [comment]
change the function bbox_ciou():
    ar_gt = boxes2[..., 2] / (boxes2[..., 3] + 0.000001)
    ar_pred = boxes1[..., 2] / (boxes1[..., 3] + 0.000001)
