### ISSUE TITLE
Video path in demo

### ISSUE THREAD

**Issue by dsantiago** [pythonlessons/TensorFlow-2.x-YOLOv3#15]
The MP4 file:

video_path   = "./IMAGES/street_drive.mp4"

in detection_demo.py is not versioned, maybe you can add in README the url to download it.

**Comment by pythonlessons** [comment]
it doesn't matter what video you will pick, but I can add a link if you really need it

**Comment by dsantiago** [comment]
Ohh sure, maybe you could change to something like :

video_path = "./IMAGES/your_video.mp4"

so it would be more clear that people need to provide the video... I was looking for some mp4 file versioned in IMAGES folder

**Comment by pythonlessons** [comment]
> Ohh sure, maybe you could change to something like :
> 
> video_path = "./IMAGES/your_video.mp4"
> 
> so it would be more clear that people need to provide the video... I was looking for some mp4 file versioned in IMAGES folder

Ok, will do that

**Comment by pythonlessons** [comment]
Added `video_path   = "./IMAGES/test.mp4"`
