### ISSUE TITLE
Center coordinates 

### ISSUE THREAD

**Issue by AMYEY** [pythonlessons/TensorFlow-2.x-YOLOv3#152]
How to get the center coordinates of the final bounding boxes? The `track.to_tlbr()` method converts to the format (min x, min y, max x, max y). But how to get the center_x, center_y of the final boxes?

**Comment by pythonlessons** [comment]
you can write a method to do that, but what you need is max_x/2-min_x/2 and max_y/2-min_y/2
you can write a function similar to track.to_tlbr() to get track.xywh or simply center...

**Comment by AMYEY** [comment]
Thank you for this
