### ISSUE TITLE
Trained on 3 object classes, but detecting only 1 class, which the first named on class names txt.file

### ISSUE THREAD

**Issue by jenapss** [pythonlessons/TensorFlow-2.x-YOLOv3#16]
Trained yolo_tiny on 3 object classes that are: carrot, cucumber and zucchini. But detection works only for that class which is first mentioned on class names txt file

**Comment by jenapss** [comment]
https://drive.google.com/drive/folders/1yG2nZLgyFqbD0DL-Wa2R0RcDetuuiTA_?usp=sharing

@pythonlessons Hello again:) Can you have a look on scripts on Google Colab, I trained to detect 3 object classes but it detects only 1 object, which is first mentioned in txt file that is used for listing class names. If you put Carrot on first place, it detects only carrot, if zucchini then it detects only zucchini

**Comment by jenapss** [comment]
it has already trained weigths for yolo-tiny detecting these 3 classes in checkpoint folder, you can just download the class names  txt file and run it locally on webcam. Thank you🙏🏻

**Comment by pythonlessons** [comment]
> it has already trained weigths for yolo-tiny detecting these 3 classes in checkpoint folder, you can just download the class names txt file and run it locally on webcam. Thank you🙏🏻

I haven't checked you carrots yet, but let me know if you still want me to look at it, otherwise close this issue, please :)

**Comment by pythonlessons** [comment]
No update
