### ISSUE TITLE
Is it posibble to get the object detected?

### ISSUE THREAD

**Issue by yuanqinong** [pythonlessons/TensorFlow-2.x-YOLOv3#163]
I am doing custom object detection with Yolov3 and run in Raspberry Pi. I am facing an issue that is getting the result(object detected). For example, when my Raspberry Pi detected a cow, and I need to pass the result to if-else statement, if the object detected is a cow, and it will send an alert, else is other animals like dog, and it will not send alert. Thus, I finding the way to get the result of object detected.

**Comment by Gekkoug** [comment]
> I'm doing something similar to check if there is a person in a video:
> 
> ```
>         bounding_boxes = [np.reshape(x, (-1, np.shape(x)[-1])) for x in pred_bbox]
>         bounding_boxes = np.concatenate(bounding_boxes, axis=0)
>         bounding_b = postprocess_boxes(bounding_boxes, frame, YOLO_INPUT_SIZE, 0.3)
>         bounding_b = nms(bounding_b, 0.1, method='nms')
> 
>         boxes = []
>         for bb in bounding_b:
>             if NUM_CLASS[int(bb[5])] == 'person':
>                 boxes.append(bb)
> ```

thanks friend. Your comment served me and saved me :).

**Comment by pythonlessons** [comment]
Solved.
