### ISSUE TITLE
Training in multiple GPUs

### ISSUE THREAD

**Issue by NaveenVinayakS** [pythonlessons/TensorFlow-2.x-YOLOv3#182]
How to train out model on multiple GPUs..

**Comment by NaveenVinayakS** [comment]
can anyone help me in this

**Comment by pythonlessons** [comment]
Hey, this implementation doesn't have the possibility to train on multiple GPUs, I don't have time to rewrite all this implementation to train on multiple GPU

**Comment by NaveenVinayakS** [comment]
Hi , can you give some reference how to implement this in multiGPU
