### ISSUE TITLE
How can we extract predictions in text format for both video and image format

### ISSUE THREAD

**Issue by gowtham-star** [pythonlessons/TensorFlow-2.x-YOLOv3#20]
Text should have all predictions with co-ordinates, class name, confidence

**Comment by pythonlessons** [comment]
> Text should have all predictions with co-ordinates, class name, confidence

go to yolov3/utils.py, find the function you are using and there you can edit these things

**Comment by gowtham-star** [comment]
Can you explain how to do it please?
