### ISSUE TITLE
Predictions in text format

### ISSUE THREAD

**Issue by gowtham-star** [pythonlessons/TensorFlow-2.x-YOLOv3#22]
Hi sir

Can you help me in code for conversion of predictions to text format for detect_image and detect_video

Thanks in advance

**Comment by pythonlessons** [comment]
> Hi sir
> 
> Can you help me in code for conversion of predictions to text format for detect_image and detect_video
> 
> Thanks in advance

This is a beginner's task, all tasks take time, best way to learn is to implement this by your self. Same as all people, I am not working for free (time is money), if you don't know how to do this by your self and you don't want to learn this you can always pay for other's time and the job they do. So, if you want me to do a specific task, you can write to me thought pythonlessons0@gmail.com and we'll consider the price (40$ for taking this job, +30$ every hour)
