### ISSUE TITLE
object-tracker.py error

### ISSUE THREAD

**Issue by avashist003** [pythonlessons/TensorFlow-2.x-YOLOv3#26]
Hey, 

The detection runs great without any issue (amazing work!), but when I used the object_tracker.py for testing, I get an error stating

**"KeyError: "The name 'images:0' refers to a Tensor which does not exist. The operation, 'images', does not exist in the graph."**

Am I missing something ?

screenshot of the terminal:

<img width="1345" alt="Screen Shot 2020-07-22 at 4 11 12 PM" src="https://user-images.githubusercontent.com/13079690/88224224-8672a680-cc1d-11ea-9ec9-0752d09fd629.png">

**Comment by pythonlessons** [comment]
I know what is the problem, but you shouldn't receive this...
Open deep_sort/generate_detections.py script
edit class ImageEncoder(object):
insert "for i in tf.get_default_graph().get_operations(): print(i.name)" line before "self.input_var = tf.get_default_graph().get_tensor_by_name(input_name)", should look following:
```
class ImageEncoder(object):
    def __init__(self, checkpoint_filename, input_name="images", output_name="features"):
        self.session = tf.Session()
        with tf.gfile.GFile(checkpoint_filename, "rb") as file_handle:
            graph_def = tf.GraphDef()
            graph_def.ParseFromString(file_handle.read())
        tf.import_graph_def(graph_def)
        for i in tf.get_default_graph().get_operations(): print(i.name)
        self.input_var = tf.get_default_graph().get_tensor_by_name(input_name)
        self.output_var = tf.get_default_graph().get_tensor_by_name(output_name)

        assert len(self.output_var.get_shape()) == 2
        assert len(self.input_var.get_shape()) == 4
        self.feature_dim = self.output_var.get_shape().as_list()[-1]
        self.image_shape = self.input_var.get_shape().as_list()[1:]

    def __call__(self, data_x, batch_size=32):
        out = np.zeros((len(data_x), self.feature_dim), np.float32)
        _run_in_batches(
            lambda x: self.session.run(self.output_var, feed_dict=x),
            {self.input_var: data_x}, out, batch_size)
        return out
```
and print here the output while you run the tracker

**Comment by avashist003** [comment]
"That's what I get on the terminal and after that it's the same error as I mentioned in the post":

import/images
import/Cast
import/map/Shape
import/map/strided_slice/stack
import/map/strided_slice/stack_1
import/map/strided_slice/stack_2
import/map/strided_slice
import/map/TensorArray
import/map/TensorArrayUnstack/Shape
import/map/TensorArrayUnstack/strided_slice/stack
import/map/TensorArrayUnstack/strided_slice/stack_1
import/map/TensorArrayUnstack/strided_slice/stack_2
import/map/TensorArrayUnstack/strided_slice
import/map/TensorArrayUnstack/range/start
import/map/TensorArrayUnstack/range/delta
import/map/TensorArrayUnstack/range
import/map/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3
import/map/Const
import/map/TensorArray_1
import/map/while/Enter
import/map/while/Enter_1
import/map/while/Merge
import/map/while/Merge_1
import/map/while/Less/Enter
import/map/while/Less
import/map/while/LoopCond
import/map/while/Switch
import/map/while/Switch_1
import/map/while/Identity
import/map/while/Identity_1
import/map/while/TensorArrayReadV3/Enter
import/map/while/TensorArrayReadV3/Enter_1
import/map/while/TensorArrayReadV3
import/map/while/strided_slice/stack
import/map/while/strided_slice/stack_1
import/map/while/strided_slice/stack_2
import/map/while/strided_slice
import/map/while/TensorArrayWrite/TensorArrayWriteV3/Enter
import/map/while/TensorArrayWrite/TensorArrayWriteV3
import/map/while/add/y
import/map/while/add
import/map/while/NextIteration
import/map/while/NextIteration_1
import/map/while/Exit_1
import/map/TensorArrayStack/TensorArraySizeV3
import/map/TensorArrayStack/range/start
import/map/TensorArrayStack/range/delta
import/map/TensorArrayStack/range
import/map/TensorArrayStack/TensorArrayGatherV3
import/conv1_1/weights
import/conv1_1/weights/read
import/conv1_1/Conv2D
import/conv1_1/conv1_1/bn/Const
import/conv1_1/conv1_1/bn/beta
import/conv1_1/conv1_1/bn/beta/read
import/conv1_1/conv1_1/bn/moving_mean
import/conv1_1/conv1_1/bn/moving_mean/read
import/conv1_1/conv1_1/bn/moving_variance
import/conv1_1/conv1_1/bn/moving_variance/read
import/conv1_1/conv1_1/bn/FusedBatchNorm
import/conv1_1/Elu
import/conv1_2/weights
import/conv1_2/weights/read
import/conv1_2/Conv2D
import/conv1_2/conv1_2/bn/Const
import/conv1_2/conv1_2/bn/beta
import/conv1_2/conv1_2/bn/beta/read
import/conv1_2/conv1_2/bn/moving_mean
import/conv1_2/conv1_2/bn/moving_mean/read
import/conv1_2/conv1_2/bn/moving_variance
import/conv1_2/conv1_2/bn/moving_variance/read
import/conv1_2/conv1_2/bn/FusedBatchNorm
import/conv1_2/Elu
import/pool1/MaxPool
import/conv2_1/1/weights
import/conv2_1/1/weights/read
import/conv2_1/1/Conv2D
import/conv2_1/1/conv2_1/1/bn/Const
import/conv2_1/1/conv2_1/1/bn/beta
import/conv2_1/1/conv2_1/1/bn/beta/read
import/conv2_1/1/conv2_1/1/bn/moving_mean
import/conv2_1/1/conv2_1/1/bn/moving_mean/read
import/conv2_1/1/conv2_1/1/bn/moving_variance
import/conv2_1/1/conv2_1/1/bn/moving_variance/read
import/conv2_1/1/conv2_1/1/bn/FusedBatchNorm
import/conv2_1/1/Elu
import/Dropout/Identity
import/conv2_1/2/weights
import/conv2_1/2/weights/read
import/conv2_1/2/biases
import/conv2_1/2/biases/read
import/conv2_1/2/Conv2D
import/conv2_1/2/BiasAdd
import/add
import/conv2_3/bn/Const
import/conv2_3/bn/beta
import/conv2_3/bn/beta/read
import/conv2_3/bn/moving_mean
import/conv2_3/bn/moving_mean/read
import/conv2_3/bn/moving_variance
import/conv2_3/bn/moving_variance/read
import/conv2_3/bn/FusedBatchNorm
import/Elu
import/conv2_3/1/weights
import/conv2_3/1/weights/read
import/conv2_3/1/Conv2D
import/conv2_3/1/conv2_3/1/bn/Const
import/conv2_3/1/conv2_3/1/bn/beta
import/conv2_3/1/conv2_3/1/bn/beta/read
import/conv2_3/1/conv2_3/1/bn/moving_mean
import/conv2_3/1/conv2_3/1/bn/moving_mean/read
import/conv2_3/1/conv2_3/1/bn/moving_variance
import/conv2_3/1/conv2_3/1/bn/moving_variance/read
import/conv2_3/1/conv2_3/1/bn/FusedBatchNorm
import/conv2_3/1/Elu
import/Dropout_1/Identity
import/conv2_3/2/weights
import/conv2_3/2/weights/read
import/conv2_3/2/biases
import/conv2_3/2/biases/read
import/conv2_3/2/Conv2D
import/conv2_3/2/BiasAdd
import/add_1
import/conv3_1/bn/Const
import/conv3_1/bn/beta
import/conv3_1/bn/beta/read
import/conv3_1/bn/moving_mean
import/conv3_1/bn/moving_mean/read
import/conv3_1/bn/moving_variance
import/conv3_1/bn/moving_variance/read
import/conv3_1/bn/FusedBatchNorm
import/Elu_1
import/conv3_1/1/weights
import/conv3_1/1/weights/read
import/conv3_1/1/Conv2D
import/conv3_1/1/conv3_1/1/bn/Const
import/conv3_1/1/conv3_1/1/bn/beta
import/conv3_1/1/conv3_1/1/bn/beta/read
import/conv3_1/1/conv3_1/1/bn/moving_mean
import/conv3_1/1/conv3_1/1/bn/moving_mean/read
import/conv3_1/1/conv3_1/1/bn/moving_variance
import/conv3_1/1/conv3_1/1/bn/moving_variance/read
import/conv3_1/1/conv3_1/1/bn/FusedBatchNorm
import/conv3_1/1/Elu
import/Dropout_2/Identity
import/conv3_1/2/weights
import/conv3_1/2/weights/read
import/conv3_1/2/biases
import/conv3_1/2/biases/read
import/conv3_1/2/Conv2D
import/conv3_1/2/BiasAdd
import/conv3_1/projection/weights
import/conv3_1/projection/weights/read
import/conv3_1/projection/Conv2D
import/add_2
import/conv3_3/bn/Const
import/conv3_3/bn/beta
import/conv3_3/bn/beta/read
import/conv3_3/bn/moving_mean
import/conv3_3/bn/moving_mean/read
import/conv3_3/bn/moving_variance
import/conv3_3/bn/moving_variance/read
import/conv3_3/bn/FusedBatchNorm
import/Elu_2
import/conv3_3/1/weights
import/conv3_3/1/weights/read
import/conv3_3/1/Conv2D
import/conv3_3/1/conv3_3/1/bn/Const
import/conv3_3/1/conv3_3/1/bn/beta
import/conv3_3/1/conv3_3/1/bn/beta/read
import/conv3_3/1/conv3_3/1/bn/moving_mean
import/conv3_3/1/conv3_3/1/bn/moving_mean/read
import/conv3_3/1/conv3_3/1/bn/moving_variance
import/conv3_3/1/conv3_3/1/bn/moving_variance/read
import/conv3_3/1/conv3_3/1/bn/FusedBatchNorm
import/conv3_3/1/Elu
import/Dropout_3/Identity
import/conv3_3/2/weights
import/conv3_3/2/weights/read
import/conv3_3/2/biases
import/conv3_3/2/biases/read
import/conv3_3/2/Conv2D
import/conv3_3/2/BiasAdd
import/add_3
import/conv4_1/bn/Const
import/conv4_1/bn/beta
import/conv4_1/bn/beta/read
import/conv4_1/bn/moving_mean
import/conv4_1/bn/moving_mean/read
import/conv4_1/bn/moving_variance
import/conv4_1/bn/moving_variance/read
import/conv4_1/bn/FusedBatchNorm
import/Elu_3
import/conv4_1/1/weights
import/conv4_1/1/weights/read
import/conv4_1/1/Conv2D
import/conv4_1/1/conv4_1/1/bn/Const
import/conv4_1/1/conv4_1/1/bn/beta
import/conv4_1/1/conv4_1/1/bn/beta/read
import/conv4_1/1/conv4_1/1/bn/moving_mean
import/conv4_1/1/conv4_1/1/bn/moving_mean/read
import/conv4_1/1/conv4_1/1/bn/moving_variance
import/conv4_1/1/conv4_1/1/bn/moving_variance/read
import/conv4_1/1/conv4_1/1/bn/FusedBatchNorm
import/conv4_1/1/Elu
import/Dropout_4/Identity
import/conv4_1/2/weights
import/conv4_1/2/weights/read
import/conv4_1/2/biases
import/conv4_1/2/biases/read
import/conv4_1/2/Conv2D
import/conv4_1/2/BiasAdd
import/conv4_1/projection/weights
import/conv4_1/projection/weights/read
import/conv4_1/projection/Conv2D
import/add_4
import/conv4_3/bn/Const
import/conv4_3/bn/beta
import/conv4_3/bn/beta/read
import/conv4_3/bn/moving_mean
import/conv4_3/bn/moving_mean/read
import/conv4_3/bn/moving_variance
import/conv4_3/bn/moving_variance/read
import/conv4_3/bn/FusedBatchNorm
import/Elu_4
import/conv4_3/1/weights
import/conv4_3/1/weights/read
import/conv4_3/1/Conv2D
import/conv4_3/1/conv4_3/1/bn/Const
import/conv4_3/1/conv4_3/1/bn/beta
import/conv4_3/1/conv4_3/1/bn/beta/read
import/conv4_3/1/conv4_3/1/bn/moving_mean
import/conv4_3/1/conv4_3/1/bn/moving_mean/read
import/conv4_3/1/conv4_3/1/bn/moving_variance
import/conv4_3/1/conv4_3/1/bn/moving_variance/read
import/conv4_3/1/conv4_3/1/bn/FusedBatchNorm
import/conv4_3/1/Elu
import/Dropout_5/Identity
import/conv4_3/2/weights
import/conv4_3/2/weights/read
import/conv4_3/2/biases
import/conv4_3/2/biases/read
import/conv4_3/2/Conv2D
import/conv4_3/2/BiasAdd
import/add_5
import/Flatten/flatten/Shape
import/Flatten/flatten/strided_slice/stack
import/Flatten/flatten/strided_slice/stack_1
import/Flatten/flatten/strided_slice/stack_2
import/Flatten/flatten/strided_slice
import/Flatten/flatten/Reshape/shape/1
import/Flatten/flatten/Reshape/shape
import/Flatten/flatten/Reshape
import/Dropout_6/Identity
import/fc1/weights
import/fc1/weights/read
import/fc1/MatMul
import/fc1/fc1/bn/Reshape/shape
import/fc1/fc1/bn/Reshape
import/fc1/fc1/bn/beta
import/fc1/fc1/bn/beta/read
import/fc1/fc1/bn/Const
import/fc1/fc1/bn/moving_mean
import/fc1/fc1/bn/moving_mean/read
import/fc1/fc1/bn/moving_variance
import/fc1/fc1/bn/moving_variance/read
import/fc1/fc1/bn/FusedBatchNorm
import/fc1/fc1/bn/Shape
import/fc1/fc1/bn/Reshape_1
import/fc1/Elu
import/ball/Reshape/shape
import/ball/Reshape
import/ball/beta
import/ball/beta/read
import/ball/Const
import/ball/moving_mean
import/ball/moving_mean/read
import/ball/moving_variance
import/ball/moving_variance/read
import/ball/FusedBatchNorm
import/ball/Shape
import/ball/Reshape_1
import/Const
import/Square
import/Sum/reduction_indices
import/Sum
import/add_6
import/Sqrt
import/truediv
import/features

**Comment by pythonlessons** [comment]
Can you try changing
def __init__(self, checkpoint_filename, input_name="images", output_name="features"):
to
def __init__(self, checkpoint_filename, input_name="*images", output_name="*features"):

**Comment by avashist003** [comment]
That also resulted in same issue after changing to "*images" and "*features"

**Comment by pythonlessons** [comment]
Replace to following function and let me know if works:
```
class ImageEncoder(object):

    def __init__(self, checkpoint_filename, input_name="images", output_name="features"):
        self.session = tf.Session()
        with tf.gfile.GFile(checkpoint_filename, "rb") as file_handle:
            graph_def = tf.GraphDef()
            graph_def.ParseFromString(file_handle.read())
        tf.import_graph_def(graph_def)
        try:
            self.input_var = tf.get_default_graph().get_tensor_by_name(input_name)
            self.output_var = tf.get_default_graph().get_tensor_by_name(output_name)
        except KeyError:
            layers = [i.name for i in tf.get_default_graph().get_operations()]
            self.input_var = tf.get_default_graph().get_tensor_by_name(layers[0]+':0')
            self.output_var = tf.get_default_graph().get_tensor_by_name(layers[-1]+':0')            

        assert len(self.output_var.get_shape()) == 2
        assert len(self.input_var.get_shape()) == 4
        self.feature_dim = self.output_var.get_shape().as_list()[-1]
        self.image_shape = self.input_var.get_shape().as_list()[1:]

    def __call__(self, data_x, batch_size=32):
        out = np.zeros((len(data_x), self.feature_dim), np.float32)
        _run_in_batches(
            lambda x: self.session.run(self.output_var, feed_dict=x),
            {self.input_var: data_x}, out, batch_size)
        return out
```

**Comment by avashist003** [comment]
Perfect! that worked.

**Comment by abhinavatai** [comment]
Hey, Do you have any idea how to transform this ImageEncoder to use with opencv dnn module?
