### ISSUE TITLE
License

### ISSUE THREAD

**Issue by FussnerS** [pythonlessons/TensorFlow-2.x-YOLOv3#29]
Hello,

I just wanted to thank you for all of the hard work you've put into producing, maintaining, and giving tutorials on your code. I am working on a project and would like to use your code if possible. Apparently, without a license, no one can really legally use your code (https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license). I was wondering if you would be willing to add a license for the project?

Thanks again,

Steven

**Comment by pythonlessons** [comment]
> Hello,
> 
> I just wanted to thank you for all of the hard work you've put into producing, maintaining, and giving tutorials on your code. I am working on a project and would like to use your code if possible. Apparently, without a license, no one can really legally use your code (https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license). I was wondering if you would be willing to add a license for the project?
> 
> Thanks again,
> 
> Steven

Added license to code 🥇

**Comment by FussnerS** [comment]
Awesome. Thank you so much!
