### ISSUE TITLE
Training save file

### ISSUE THREAD

**Issue by DanielDomaracki** [pythonlessons/TensorFlow-2.x-YOLOv3#3]
Hello,

Thank you very much for writing all this code, it is incredible. Unfortunately I can't seem to find the save file of the retrained weights. This is my final readout after running train.py with the newly configured config file. I did have it set to 30 epochs so it did do the full amount.

epoch:30 step:   92/93, lr:0.000001, giou_loss:   4.07, conf_loss:   1.96, prob_loss:   0.48, total_loss:   6.52
epoch:30 step:    0/93, lr:0.000001, giou_loss:   0.58, conf_loss:   1.65, prob_loss:   0.11, total_loss:   2.35
epoch:30 step:    1/93, lr:0.000001, giou_loss:   3.67, conf_loss:   2.23, prob_loss:   0.46, total_loss:   6.36

giou_val_loss:   3.37, conf_val_loss:   2.31, prob_val_loss:   0.36, total_val_loss:   6.05

**Comment by pythonlessons** [comment]
Hello, are you sure that it's not saving? What files you see in checkpoints folder?

**Comment by DanielDomaracki** [comment]
In my logs folder i have 2 events files that end in v2 and the checkpoint files are:

checkpoint
yolov3_custom.data-00000-of-00002
yolov3_custom.data-00001-of-00002
yolov3_custom.index

The 1 of 2 file is about weight size at 240 MB but doesn't have a .weight extension. I added that extension thinking this might be the file but it wasnt then able to detect my images.

Thank you for your response

**Comment by pythonlessons** [comment]
Here is your model
> yolov3_custom.data-00000-of-00002
> yolov3_custom.data-00001-of-00002
> yolov3_custom.index

Try to detect with `yolov3_custom` without .weight extension

**Comment by DanielDomaracki** [comment]
Sorry I'm not understanding well. In "detection_demo.py" I have this now:

```
input_size = YOLO_INPUT_SIZE
#Darknet_weights = YOLO_DARKNET_WEIGHTS
Darknet_weights = "./checkpoints/yolov3_custom"

image_path   = "./IMAGES/001.png"
video_path   = "./IMAGES/city_drive.mp4"
```
for the weights path I had only "yolov3_custom" "yolov3_custom.index" and yolov3_custom.data-00001-of-00002"

With each of these weights I keep getting a reshape error similar to:

`20-05-17 16:42:46.767068: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "C:\Users\danie\Documents\Code\TensorFlow-2.x-YOLOv3-master\detection_demo.py", line 29, in <module>
    load_yolo_weights(yolo, Darknet_weights) # use Darknet weights
  File "C:\Users\danie\Documents\Code\TensorFlow-2.x-YOLOv3-master\yolov3\utils.py", line 56, in load_yolo_weights
    conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0])
ValueError: cannot reshape array of size 4814 into shape (64,32,3,3)`

except the array size number changes

**Comment by pythonlessons** [comment]
Tomorrow I will upload new tutorial with custom detection, and will upload new script for custom detection, wait for one day

**Comment by DanielDomaracki** [comment]
Okay, not a problem. Thank you so much

**Comment by robisen1** [comment]
> Tomorrow I will upload new tutorial with custom detection, and will upload new script for custom detection, wait for one day

I am having this exact same issue. I trained on a few hundred epochs and when it ended I found the same thing as Daniel. What was the resolution for this?
