### ISSUE TITLE
train yolov4

### ISSUE THREAD

**Issue by bagaseko1** [pythonlessons/TensorFlow-2.x-YOLOv3#30]
i train use yolov4 but get error
" Duplicate node name in graph: 'ones' " in yolov4.py line 420

**Comment by pythonlessons** [comment]
what tf version you use?

**Comment by bagaseko1** [comment]
i use tf 2.2

**Comment by pythonlessons** [comment]
Can you try `pip install tensorflow==2.3.0rc0 ` and let me know the results because I am developing on this version now

**Comment by pythonlessons** [comment]
Did you tried?

**Comment by bagaseko1** [comment]
not yet, i will try tomorrow maybe

**Comment by pythonlessons** [comment]
NO UPDATE
