### ISSUE TITLE
Error: evaluate.py

### ISSUE THREAD

**Issue by deeplearner93** [pythonlessons/TensorFlow-2.x-YOLOv3#35]
Thank you @pythonlessons  for the detailed steps and neat documentation.
I wanted to evaluate my custom trained model. I have the weight file, renamed as "yolov3.weights" for simplicity and pasted in "model_data".

I changed the following
- TRAIN_CLASSES to 'model_data/coco/coco.names' - DONE
- If you wanna train on COCO dataset, change TRAIN_ANNOT_PATH to 'model_data/coco/train2017.txt' - DONE
- To validate the model on COCO dataset change TEST_ANNOT_PATH to 'model_data/coco/val2017.txt' - DONE

I tried running the "evaluate.py", it was taking a Long time, my GPU resource was not used. Therefore I tried with 300 Images to check if I get the desired Output as mentioned. But I got the following error, even though , the "coco.names" file contains the class CAR and one of my Images had a CAR object in the Picture.

``` 
Traceback (most recent call last):
  File "evaluate_mAP.py", line 282, in <module>
    get_mAP(yolo, testset, score_threshold=0.05, iou_threshold=0.50)
  File "evaluate_mAP.py", line 157, in get_mAP
    json_pred[gt_classes.index(class_name)].append({"confidence": str(score), "file_id": str(index), "bbox": str(bbox)})
ValueError: 'car' is not in list
 
````
could not debug, request update/support.

Thank you in advance

**Comment by pythonlessons** [comment]
Can you first download COCO test dataset and move it to `TensorFlow-2.x-YOLOv3/model_data/coco/` folder.
Download original yolov3 or yolov4 weights and place it to model_data folder.
Change `TRAIN_CLASSES' to "model_data/coco/coco.names"
Change `TEST_ANNOT_PATH` to "model_data/coco/val2017.txt"

If everything works, then change `YOLO_CUSTOM_WEIGHTS` to your `weights_file_name_location`
Let me know if it works.

Also it's by default everything is configured to train and evaluate custom mnist dataset. You can try to train it for several epochs to test it out

**Comment by deeplearner93** [comment]
> 
> 
> Can you first download COCO test dataset and move it to `TensorFlow-2.x-YOLOv3/model_data/coco/` folder.
> Download original yolov3 or yolov4 weights and place it to model_data folder.
> Change `TRAIN_CLASSES' to "model_data/coco/coco.names" Change `TEST_ANNOT_PATH` to "model_data/coco/val2017.txt"
> 
> If everything works, then change `YOLO_CUSTOM_WEIGHTS` to your `weights_file_name_location`
> Let me know if it works.
> 
> Also it's by default everything is configured to train and evaluate custom mnist dataset. You can try to train it for several epochs to test it out

**Comment by deeplearner93** [comment]
> 
> 
> > Can you first download COCO test dataset and move it to `TensorFlow-2.x-YOLOv3/model_data/coco/` folder.
> > Download original yolov3 or yolov4 weights and place it to model_data folder.
> > Change `TRAIN_CLASSES' to "model_data/coco/coco.names" Change `TEST_ANNOT_PATH` to "model_data/coco/val2017.txt"
> > If everything works, then change `YOLO_CUSTOM_WEIGHTS` to your `weights_file_name_location`
> > Let me know if it works.
> > Also it's by default everything is configured to train and evaluate custom mnist dataset. You can try to train it for several epochs to test it out

Thank you. I followed your steps. Works fine.!!

**Comment by avid1894** [comment]
Hello @pythonlessons , 
I have the same error so I changed YOLO_CUSTOM_WEIGHTS         = "checkpoints/yolov3_custom" from False. I am training on my own set of images & classes. After I changed to this, the "ValueError: 'audio' is not in list" is not seen, but I am getting the unboundlocalerror "local variable 'save_directory' referenced before assignment"
