### ISSUE TITLE
Evaluation of Yolov3

### ISSUE THREAD

**Issue by hiteshkhanna31** [pythonlessons/TensorFlow-2.x-YOLOv3#4]
Hi Sir, 
Thank you for great work.

I am trying to evaluate the mAP for Yolov3 but i am facing a issue with the coordinate of the grounth truth and prediction Bounding Box.

For example the grouth truth for a object in a image of MS-coco are "167.89 182.09 301.96 205.34" and the coordinate predicted by the utils.py for bounding box are "**170.19602966 181.54490662 469.15988159 397.06906128**".

I think the format for the grouth truth and prediction are not matching which results in wrong mAP. Please appreciate your help as i am a beginner in computer vision domain.

Thank you
Hitesh

**Comment by pythonlessons** [comment]
Thanks for this, quite soon I plan to implement mAP, was not looking at it yet
