### ISSUE TITLE
Cannot save in train.py

### ISSUE THREAD

**Issue by nn-devs** [pythonlessons/TensorFlow-2.x-YOLOv3#40]
After finishing the training, I get an unboundlocalerror: local variable 'save directory' referenced before assignment.
How can I resolve this issue?

**Comment by pythonlessons** [comment]
> After finishing the training, I get an unboundlocalerror: local variable 'save directory' referenced before assignment.
> How can I resolve this issue?

but weights are saved every epoch?

**Comment by nn-devs** [comment]
> > After finishing the training, I get an unboundlocalerror: local variable 'save directory' referenced before assignment.
> > How can I resolve this issue?
> 
> but weights are saved every epoch?

No. Only thing that is saved is the data file when I have TRAIN_SAVE_CHECKPOINT set to True.
This unbound local error occurs at line 177 on train.py.

Slightly off topic but I get CUDA_ERROR_NO_DEVICE when running train.py, but if I run the detection it can utilise my GPU.
Not sure why it won't work on train.py.

**Comment by YanAwithU** [comment]
> > > After finishing the training, I get an unboundlocalerror: local variable 'save directory' referenced before assignment.
> > > How can I resolve this issue?
> > 
> > 
> > but weights are saved every epoch?
> 
> No. Only thing that is saved is the data file when I have TRAIN_SAVE_CHECKPOINT set to True.
> This unbound local error occurs at line 177 on train.py.
> 
> Slightly off topic but I get CUDA_ERROR_NO_DEVICE when running train.py, but if I run the detection it can utilise my GPU.
> Not sure why it won't work on train.py.

https://github.com/pythonlessons/TensorFlow-2.x-YOLOv3/issues/45#issue-694203551
I made new issue for gpu error. I wrote details about it. Look at it please.

**Comment by pythonlessons** [comment]
Seems it was solved
