### ISSUE TITLE
ValueError: Dimension 1 in both shapes must be equal, but are 38 and 26

### ISSUE THREAD

**Issue by YanAwithU** [pythonlessons/TensorFlow-2.x-YOLOv3#43]
I wanna train custom model, so I followed guide.
I changed `config.py` YOLO_INPUT_SIZE 416 to 608(accrording to guide).
Than error occured.
`ValueError: Dimension 1 in both shapes must be equal, but are 38 and 26. Shapes are [4,38,38] and [4,26,26]. for '{{node concat_6}} = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32, _cloned=true](inputs, inputs_1, concat_6/axis)' with input shapes: [4,38,38,128], [4,26,26,256], [] and with computed input tensors: input[2] = <-1>.`

How can I fix it?? Doesn't it need to change?

**Comment by YanAwithU** [comment]
Oh, I used yolo v4 tiny because I wanna convert it to TF lite model. By the way  it worked before changed value.

**Comment by bedna-KU** [comment]
You must have same values in configs.py:
YOLO_INPUT_SIZE
TRAIN_INPUT_SIZE
TEST_INPUT_SIZE

**Comment by YanAwithU** [comment]
I solved this problem by changing all input size 608(YOLO,TRAIN,TEST). Thanks to guy who mailed me.

**Comment by julio8a** [comment]
what is sized to 608?

**Comment by YanAwithU** [comment]
@julio8a 
You can find yolov3/configs.py in this repository. I changed all constants named 'INPUT_SIZE' to 608. Than it worked!
Good luck.
