### ISSUE TITLE
ImportError: cannot import name 'trt_convert' from 'tensorflow.python.compiler.tensorrt'

### ISSUE THREAD

**Issue by chull434** [pythonlessons/TensorFlow-2.x-YOLOv3#49]
Hi, 

trying to run convert_to_trt.py

getting 'ImportError: cannot import name 'trt_convert' from 'tensorflow.python.compiler.tensorrt''

am i missing a package or something, i have tensor flow 2.3.0 as per the requirements file

**Comment by pythonlessons** [comment]
Have you installed tensorrt on your computer?

**Comment by pythonlessons** [comment]
No answer?
