### ISSUE TITLE
Checkpoint learning on Colab error

### ISSUE THREAD

**Issue by IamJesus219** [pythonlessons/TensorFlow-2.x-YOLOv3#5]
This has been really helpful, thank you! 

I'm having an issue using checkpoint learning on colab, it's not working and returns an error;

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/network.py in _is_hdf5_filepath(filepath)
AttributeError: 'bool' object has no attribute 'endswith'

**Comment by pythonlessons** [comment]
> This has been really helpful, thank you!
> 
> I'm having an issue using checkpoint learning on colab, it's not working and returns an error;
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/network.py in _is_hdf5_filepath(filepath)
> AttributeError: 'bool' object has no attribute 'endswith'

Will test it later by my self
