### ISSUE TITLE
failed to read all data by train.py

### ISSUE THREAD

**Issue by LionAaron** [pythonlessons/TensorFlow-2.x-YOLOv3#52]
The Issue:
Traceback (most recent call last):
  File "C:/Users/ms/Documents/YOLOv4/TensorFlow-2.x-YOLOv3/train.py", line 184, in <module>
    main()
  File "C:/Users/ms/Documents/YOLOv4/TensorFlow-2.x-YOLOv3/train.py", line 53, in main
    load_yolo_weights(Darknet, Darknet_weights) # use darknet weights
  File "C:\Users\ms\Documents\YOLOv4\TensorFlow-2.x-YOLOv3\yolov3\utils.py", line 71, in load_yolo_weights
    assert len(wf.read()) == 0, 'failed to read all data'
AssertionError: failed to read all data
`
And my configs.py
YOLO_TYPE                             = "yolov4" # yolov4 or yolov3
YOLO_FRAMEWORK               = "tf" # "tf" or "trt"
YOLO_V3_WEIGHTS                = "model_data/yolov3.weights"
YOLO_V4_WEIGHTS                = "model_data/yolov4.weights"
YOLO_V3_TINY_WEIGHTS       = "model_data/yolov3-tiny.weights"
YOLO_V4_TINY_WEIGHTS       = "model_data/yolov4-tiny.weights"
YOLO_TRT_QUANTIZE_MODE = "INT8" # INT8, FP16, FP32
YOLO_CUSTOM_WEIGHTS      = "C:/Users/ms/Documents/YOLOv4/TensorFlow-2.x-YOLOv3/checkpoints" 
YOLO_COCO_CLASSES            = "C:/Users/ms/Documents/YOLOv4/TensorFlow-2.x-YOLOv3/SW/sw.names"
YOLO_STRIDES                        = [8, 16, 32]
YOLO_IOU_LOSS_THRESH       = 0.5
YOLO_ANCHOR_PER_SCALE   = 3
YOLO_MAX_BBOX_PER_SCALE= 100
YOLO_INPUT_SIZE                   = 416
if YOLO_TYPE                          == "yolov4":
    YOLO_ANCHORS                = [[[12,  16], [19,   36], [40,   28]],
                                                   [[36,  75], [76,   55], [72,  146]],
                                                   [[142,110], [192, 243], [459, 401]]]
if YOLO_TYPE                          == "yolov3":
    YOLO_ANCHORS                = [[[10,  13], [16,   30], [33,   23]],
                                                   [[30,  61], [62,   45], [59,  119]],
                                                   [[116, 90], [156, 198], [373, 326]]]
# Train options
TRAIN_YOLO_TINY                 = False
TRAIN_SAVE_BEST_ONLY       = True # saves only best model according validation loss (True recommended)
TRAIN_SAVE_CHECKPOINT    = True # saves all best validated checkpoints in training process (may require a lot disk space) (False recommended)
TRAIN_CLASSES                      = "C:/Users/ms/Documents/YOLOv4/TensorFlow-2.x-YOLOv3/SW/sw.names"
TRAIN_ANNOT_PATH              = "C:/Users/ms/Documents/YOLOv4/TensorFlow-2.x-YOLOv3/SW/Train_1.txt"           #"mnist/mnist_train.txt"
TRAIN_LOGDIR                        = "log"
TRAIN_CHECKPOINTS_FOLDER    = "C:/Users/ms/Documents/YOLOv4/TensorFlow-2.x-YOLOv3/checkpoints"
TRAIN_MODEL_NAME            = f"{YOLO_TYPE}_custom"
TRAIN_LOAD_IMAGES_TO_RAM    = True # With True faster training, but need more RAM
TRAIN_BATCH_SIZE                 = 4
TRAIN_INPUT_SIZE                  = 416
TRAIN_DATA_AUG                   = True
TRAIN_TRANSFER                   = True
TRAIN_FROM_CHECKPOINT   = False # "checkpoints/yolov3_custom"
TRAIN_LR_INIT                        = 1e-4
TRAIN_LR_END                       = 1e-6
TRAIN_WARMUP_EPOCHS     = 2
TRAIN_EPOCHS                      = 100

# TEST options
TEST_ANNOT_PATH                = "C:/Users/ms/Documents/YOLOv4/TensorFlow-2.x-YOLOv3/SW/Test_1.txt"
TEST_BATCH_SIZE                   = 4
TEST_INPUT_SIZE                   = 416
TEST_DATA_AUG                    = False
TEST_DECTECTED_IMAGE_PATH   = "C:/Users/ms/Documents/YOLOv4/TensorFlow-2.x-YOLOv3/IMAGES"
TEST_SCORE_THRESHOLD     = 0.3
TEST_IOU_THRESHOLD          = 0.45
`
Where is my problem?
Every file exist at the right place.

**Comment by LionAaron** [comment]
Understanding
My sw.naws only has two objects. I added 78 more lines and it worked again.
Where can I set that he should only take these 2 classes and see 80?

**Comment by pythonlessons** [comment]
Did not understand what you want.
If you train custom model with 2 classes, you will detect only 2 objects.
You can't train at 2 classes and detect 80 objects.

**Comment by LionAaron** [comment]
Yes, I only want to detect 2 objects.
When I put in sw.names my two objects:

apple
pear

Start the training and then i get the mistake:
Traceback (most recent call last):
File "C:/Users/ms/Documents/YOLOv4/TensorFlow-2.x-YOLOv3/train.py", line 184, in
main()
File "C:/Users/ms/Documents/YOLOv4/TensorFlow-2.x-YOLOv3/train.py", line 53, in main
load_yolo_weights(Darknet, Darknet_weights) # use darknet weights
File "C:\Users\ms\Documents\YOLOv4\TensorFlow-2.x-YOLOv3\yolov3\utils.py", line 71, in load_yolo_weights
assert len(wf.read()) == 0, 'failed to read all data'
AssertionError: failed to read all data

But when I write in sw.names:

Apple
pear
1
1
1
1
1
... (up to 80)

then it works, but that's :(

Can I set somewhere that it only expects 2 objects in sw.names?

**Comment by bedna-KU** [comment]
You need download YOLOv4 weight
`wget -P model_data https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.weights`

**Comment by LionAaron** [comment]
Thank you bedna-KU for your support, but i have yolov4.weights downloaded.
Now its under the path: .../TensorFlow-2.x-YOLOv3/model_data/yolov4.weights, that must be correct or not?

**Comment by pythonlessons** [comment]
Change YOLO_CUSTOM_WEIGHTS  to False

**Comment by LionAaron** [comment]
Same Error...

**Comment by pythonlessons** [comment]
Thats quite strange, there shouldn't be any error, can you try with yolov3?

**Comment by LionAaron** [comment]
Same Error.
Yeah, thats realy strange. 

Yesterday I had the problem for the first time. Then I cloned your repository again. installed the requests ,set  paths in the configs (as shown) and created the folder SW with sw.names and co inside.

I don't know where the error crept in.

**Comment by pythonlessons** [comment]
Zip your repository, put it on google drive and give me link to download it, I will test it for you if I receive same error

**Comment by LionAaron** [comment]
Wow, das ist Unterstützung! Danke dir!

Kann ich es dir ohne die Bilder schicken, diese gehören nämlich nicht mir und sind unterverschluss?

**Comment by LionAaron** [comment]
Wow, that's support!
 Nevertheless, I have to decline with thanks. I'm a student in a company and I'm not allowed to give away the pictures, objects, etc. These are under seal, thank you anyway.

**Comment by pythonlessons** [comment]
I understand you, anyway I think you are missing something. How it works with my mnist custom dataset, were you able to train on it?

**Comment by pythonlessons** [comment]
No update.

**Comment by venkatesh-sadasivam** [comment]
Hi i had the same error so i changed the code a little bit in utils.py like this
` assert len(wf.read()) == 0, 'failed to read all data'   `
                   to
`   if len(wf.read()) == 0:
            assert 'failed to read all data'`
now it is working for me but all the losses are coming as nan is it fine?
and mnist dataset trained like a charm by following your instructions.

**Comment by pythonlessons** [comment]
not really, some of layers may be not transferred, so you may be missing some neurons in your network

**Comment by Myron1996** [comment]
I am also having the error when I try to train using transfer learning. 

Traceback (most recent call last):
  File "train.py", line 205, in <module>
    main()
  File "train.py", line 73, in main
    load_yolo_weights(Darknet, Darknet_weights) # use darknet weights
  File "/qfree/docker/training/training_02/yolov3/utils.py", line 67, in load_yolo_weights
    assert len(wf.read()) == 0, 'failed to read all data'
AssertionError: failed to read all data



My config.py file 

# YOLO options
YOLO_DARKNET_WEIGHTS        = "model_data/yolov3.weights"
YOLO_DARKNET_TINY_WEIGHTS   = "model_data/yolov3-tiny.weights"
YOLO_COCO_CLASSES           = "model_data/Dataset_names.txt"
YOLO_STRIDES                = [8, 16, 32]
YOLO_IOU_LOSS_THRESH        = 0.5
YOLO_ANCHOR_PER_SCALE       = 3
YOLO_MAX_BBOX_PER_SCALE     = 100
YOLO_INPUT_SIZE             = 416
YOLO_ANCHORS                = [[[10,  13], [16,   30], [33,   23]],
                               [[30,  61], [62,   45], [59,  119]],
                               [[116, 90], [156, 198], [373, 326]]]
# Train options
TRAIN_YOLO_TINY             = False
TRAIN_SAVE_BEST_ONLY        = True # saves only best model according validation loss (True recommended)
TRAIN_SAVE_CHECKPOINT       = False # saves all best validated checkpoints in training process (may require a lot disk space) (False recommended)
TRAIN_CLASSES               = "./model_data/Dataset_names.txt"
TRAIN_ANNOT_PATH            = "./train.txt"
TRAIN_LOGDIR                = "./log"
TRAIN_CHECKPOINTS_FOLDER    = "checkpoints"
TRAIN_MODEL_NAME            = "yolov3_custom"
TRAIN_LOAD_IMAGES_TO_RAM    = True # faster training, but need more RAM
TRAIN_BATCH_SIZE            = 32
TRAIN_INPUT_SIZE            = 416
TRAIN_DATA_AUG              = True
TRAIN_TRANSFER              = True
TRAIN_FROM_CHECKPOINT       = False # "checkpoints/yolov3_custom"
TRAIN_LR_INIT               = 1e-4
TRAIN_LR_END                = 1e-6
TRAIN_WARMUP_EPOCHS         = 2
TRAIN_EPOCHS                = 1000

# TEST options
TEST_ANNOT_PATH             = "./test.txt"
TEST_BATCH_SIZE             = 4
TEST_INPUT_SIZE             = 416
TEST_DATA_AUG               = False
"configs.py" 59L, 2466C

**Comment by pythonlessons** [comment]
I see you use old configs, code is updated, may you download new version and test it again?

**Comment by Myron1996** [comment]
Hi @pythonlessons  . thanks for the quick reply . I actually been using he old version for quite a long and it was running properly before . I am not sure what exactly happened. 

Majority of development work is been done on old version so changing it entirely might be a pain. Do you have any suggestions with respect to the old version.

**Comment by venkatesh-sadasivam** [comment]
> not really, some of layers may be not transferred, so you may be missing some neurons in your network

Can you suggest a solution for that what should I do my custom dataset has 11 classes

**Comment by pythonlessons** [comment]
It's quite hard to debug, but you may then compare functions that do model loading, what are the differences there with your version, and the new one. I am not planning to do any major updates to code, so I recommend to do this last checking steps.

**Comment by venkatesh-sadasivam** [comment]
> It's quite hard to debug, but you may then compare functions that do model loading, what are the differences there with your version, and the new one. I am not planning to do any major updates to code, so I recommend to do this last checking steps.

i did not do any changes I just followed the steps provided in pylessons site and I changed the class names and train test paths according to my new dataset

**Comment by Myron1996** [comment]
Sure . Can you please tell me which versions you used to test this new code 

- CUDA

- CUDNN


- TensorRT

- Tensorflow-GPU

- is it tested only on Linux or Windows also . which version of Linux

It will be very helpful for anyone new to see the quick summery of above specs .

**Comment by pythonlessons** [comment]
Sure:

- CUDA 10.1

- cuDNN v7.6.5

- TensorRT-6.0.1.5

- Tensorflow-GPU 2.3.1

**Comment by Myron1996** [comment]
Thanks a lot @pythonlessons  . I really appreciate your support. I will post my update If i get everything working properly so that others might benefit from it.

**Comment by pythonlessons** [comment]
Thanks

**Comment by Myron1996** [comment]
Hi @pythonlessons 

I cloned the new version of repo as you suggested and I am still getting the following error 
```
File "train.py", line 184, in <module>
    main()
  File "train.py", line 53, in main
    load_yolo_weights(Darknet, Darknet_weights) # use darknet weights
  File "/qfree/docker/training/training_05/yolov3/utils.py", line 74, in load_yolo_weights
    assert len(wf.read()) == 0, 'failed to read all data'
AssertionError: failed to read all data
```
I set up the training using following settings  - I **am** using transfer learning with yolov3 weight files 

**config.py**

```

# YOLO options
YOLO_TYPE                   = "yolov3" # yolov4 or yolov3
YOLO_FRAMEWORK              = "tf" # "tf" or "trt"
YOLO_V3_WEIGHTS             = "./model_data/yolov3.weights"
#YOLO_V4_WEIGHTS             = "model_data/yolov4.weights"
#YOLO_V3_TINY_WEIGHTS        = "model_data/yolov3-tiny.weights"
#YOLO_V4_TINY_WEIGHTS        = "model_data/yolov4-tiny.weights"
#YOLO_TRT_QUANTIZE_MODE      = "INT8" # INT8, FP16, FP32
YOLO_CUSTOM_WEIGHTS         = False # "checkpoints/yolov3_custom" # used in evaluate_mAP.py and custom model detection, if not using leave False
                            # YOLO_CUSTOM_WEIGHTS also used with TensorRT and custom model detection
YOLO_COCO_CLASSES           = "model_data/dataset.names" #"model_data/coco/coco.names"
YOLO_STRIDES                = [8, 16, 32]
YOLO_IOU_LOSS_THRESH        = 0.5
YOLO_ANCHOR_PER_SCALE       = 3
YOLO_MAX_BBOX_PER_SCALE     = 100
YOLO_INPUT_SIZE             = 416
if YOLO_TYPE                == "yolov4":
    YOLO_ANCHORS            = [[[12,  16], [19,   36], [40,   28]],
                               [[36,  75], [76,   55], [72,  146]],
                               [[142,110], [192, 243], [459, 401]]]
if YOLO_TYPE                == "yolov3":
    YOLO_ANCHORS            = [[[10,  13], [16,   30], [33,   23]],
                               [[30,  61], [62,   45], [59,  119]],
                               [[116, 90], [156, 198], [373, 326]]]
# Train optionsi
TRAIN_YOLO_TINY             = False
TRAIN_SAVE_BEST_ONLY        = True # saves only best model according validation loss (True recommended)
TRAIN_SAVE_CHECKPOINT       = False # saves all best validated checkpoints in training process (may require a lot disk space) (False recommended)
TRAIN_CLASSES               = "./model_data/dataset.names" #"./mnist/mnist.names"
TRAIN_ANNOT_PATH            = "./train.txt" #"./mnist/mnist_train.txt"
TRAIN_LOGDIR                = "./log"
TRAIN_CHECKPOINTS_FOLDER    = "./checkpoints"
TRAIN_MODEL_NAME            = f"{YOLO_TYPE}_custom"
TRAIN_LOAD_IMAGES_TO_RAM    = True # With True faster training, but need more RAM
TRAIN_BATCH_SIZE            = 4
TRAIN_INPUT_SIZE            = 416
TRAIN_DATA_AUG              = True
TRAIN_TRANSFER              = True
TRAIN_FROM_CHECKPOINT       = False # "checkpoints/yolov3_custom"
TRAIN_LR_INIT               = 1e-4
TRAIN_LR_END                = 1e-6
TRAIN_WARMUP_EPOCHS         = 2
TRAIN_EPOCHS                = 100

# TEST options
TEST_ANNOT_PATH             = "./test.txt" #"./mnist/mnist_test.txt"
TEST_BATCH_SIZE             = 4
TEST_INPUT_SIZE             = 416
TEST_DATA_AUG               = False
TEST_DECTECTED_IMAGE_PATH   = ""
TEST_SCORE_THRESHOLD        = 0.3
TEST_IOU_THRESHOLD          = 0.45


#YOLOv3-TINY and YOLOv4-TINY WORKAROUND
if TRAIN_YOLO_TINY:
    YOLO_STRIDES            = [16, 32, 64]
    YOLO_ANCHORS            = [[[10,  14], [23,   27], [37,   58]],
                               [[81,  82], [135, 169], [344, 319]],
                               [[0,    0], [0,     0], [0,     0]]]
```
**dataset.names** file  - Custom Classes 
```
car
truck
car with caravan
van
motorcycle
bus
caravan
car with trailer
van with trailer
cycle
pedestrian
unknown
```
I am using yolov3.weights file from the source provided by your github repo. 

I looked some solutions for this error. so far I came across following link.   
                                                                     
[https://www.qdxingtu.com/key/AssertionError:%20failed%20to%20read%20all%20data.html](url)

Can you please help me resolve this error ?

**Comment by pythonlessons** [comment]
try this tho change:
~~YOLO_COCO_CLASSES           = "model_data/dataset.names" #"model_data/coco/coco.names"~~
YOLO_COCO_CLASSES           = "model_data/coco/coco.names"

**Comment by Myron1996** [comment]
Apologies in advanced . I am new to this YOLO but . 
I used bellow**.names** file to create a training data set using **labellmg** . 
```
car
truck
car with caravan
van
motorcycle
bus
caravan
car with trailer
van with trailer
cycle
pedestrian
unknown
```
if I change it now to **coco.names** during training then the entire training will produce wrong results because both the **.names** files are different.

**Comment by pythonlessons** [comment]
No, you use your own weights in TRAIN_CLASSES line. You must use coco classes to create original model to transfer weights from it

**Comment by Myron1996** [comment]
Awesome. It worked. Thank you @pythonlessons  👍
