### ISSUE TITLE
Yolo V3 and V4 . Custom Images datasets: Error: index 52 is out of bounds for axis 1 with size 52

### ISSUE THREAD

**Issue by ASR-Engineering-Consulting** [pythonlessons/TensorFlow-2.x-YOLOv3#55]
I am creating custom datasets, with hight resolution to detect all the strawberry growing stages for my Msc project, I got the pictures and using LabelIMG to label each. I already trained yolo v3 for a F1 car deception before. but now I am getting this  error
I am thinking about the image size could be the problem, but I already had label more than 1000 images and I will need to resize the image and annotation.

I was looking in Github for a script to test all the images before start the training to avoid wasting time.  Any ideas on how to address this issues? 

what is your suggestion? I need to use my own pictures to perform this training.
Antonio

**Comment by pythonlessons** [comment]
Everything is fine with your images, you don't need to resize them manually. 
What you did to receive this error? When you encounter it?

**Comment by ASR-Engineering-Consulting** [comment]
![image](https://user-images.githubusercontent.com/46198828/93331519-afc84100-f820-11ea-9a55-a171e47f69c2.png)

**Comment by ASR-Engineering-Consulting** [comment]
![image](https://user-images.githubusercontent.com/46198828/93331611-d8503b00-f820-11ea-85c4-e2d5f0b8a100.png)

**Comment by ASR-Engineering-Consulting** [comment]
I am looking on the dataset.py, maybe the annotation or prepocess true box

**Comment by ASR-Engineering-Consulting** [comment]
My dataset is about Strawberries and I would like to run the Archer prior box scrips to adjust to my datasets

**Comment by pythonlessons** [comment]
Did you solved this problem?
