### ISSUE TITLE
Exception shapes (255,) and (18,) are incompatible

### ISSUE THREAD

**Issue by roman-zakharov** [pythonlessons/TensorFlow-2.x-YOLOv3#57]
Trained the model in one class Person
changed in configs.py
YOLO_CUSTOM_WEIGHTS         = "checkpoints/yolov4_custom_Person_yolov4_tiny_Tiny"
and run detection_custom.py
and I get an execution
![image](https://user-images.githubusercontent.com/60859398/93572565-b086e180-f99e-11ea-82de-d9c79a2ea4f2.png)

**Comment by pythonlessons** [comment]
Download new files, updated day a go

**Comment by roman-zakharov** [comment]
thank everything worked
