### ISSUE TITLE
cannot reshape array

### ISSUE THREAD

**Issue by Rajatkhatri7** [pythonlessons/TensorFlow-2.x-YOLOv3#58]
I'm running  YOLOV3_colab_training training notebook and while m executing the cell 

import cv2
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline  
import tensorflow as tf
from yolov3.yolov4 import Create_Yolo
from yolov3.utils import load_yolo_weights, detect_image
from yolov3.configs import *

if YOLO_TYPE == "yolov4":
    Darknet_weights = YOLO_V4_TINY_WEIGHTS if TRAIN_YOLO_TINY else YOLO_V4_WEIGHTS
if YOLO_TYPE == "yolov3":
    Darknet_weights = YOLO_V3_TINY_WEIGHTS if TRAIN_YOLO_TINY else YOLO_V3_WEIGHTS

yolo = Create_Yolo(input_size=YOLO_INPUT_SIZE)
load_yolo_weights(yolo, Darknet_weights) # use Darknet weights

its giving error 

ValueError                                Traceback (most recent call last)
<ipython-input-6-14485b4687da> in <module>()
     15 
     16 yolo = Create_Yolo(input_size=YOLO_INPUT_SIZE)
---> 17 load_yolo_weights(yolo, Darknet_weights) # use Darknet weights

/content/gdrive/My Drive/TensorFlow-2.x-YOLOv3/TensorFlow-2.x-YOLOv3-master/yolov3/utils.py in load_yolo_weights(model, weights_file)
     64             conv_weights = np.fromfile(wf, dtype=np.float32, count=np.product(conv_shape))
     65             # tf shape (height, width, in_dim, out_dim)
---> 66             conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0])
     67 
     68             if i not in range2:

ValueError: cannot reshape array of size 883022 into shape (512,256,3,3)

**Comment by robisen1** [comment]
did you change the classes file at all? have you made changes to config? its basically saying what your passing to it is not shaped right, which it clearly isn't, because something like the weights, classes, inputs etc don't match what it expects
