### ISSUE TITLE
Cannot reshape array of size 391694 into shape 

### ISSUE THREAD

**Issue by prem48science** [pythonlessons/TensorFlow-2.x-YOLOv3#6]
Hi, I got this error while running the demo file in windows 10 system. 
any solution?

Traceback (most recent call last):
  File ".\detection_demo.py", line 29, in <module>
    load_yolo_weights(yolo, Darknet_weights) # use Darknet weights
  File "E:\DEV\Project_Alot\Image_Detect\TensorFlow-2.x-YOLOv3\yolov3\utils.py", line 59, in load_yolo_weights
    conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0])
ValueError: cannot reshape array of size 391694 into shape (512,256,3,3)

**Comment by pythonlessons** [comment]
For me, everything works on Windows 10. How I can reproduce your error?

**Comment by prem48science** [comment]
I just followed the instructions given in the project and I got this error. 
my python version python 3.7.7
absl-py==0.9.0
astunparse==1.6.3
attrs==19.3.0
backcall==0.1.0
bleach==3.1.5
cachetools==4.1.0
certifi==2020.4.5.1
chardet==3.0.4
colorama==0.4.3
cycler==0.10.0
Cython==0.29.19
decorator==4.4.2
defusedxml==0.6.0
entrypoints==0.3
gast==0.3.3
google-auth==1.16.0
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
grpcio==1.29.0
h5py==2.10.0
idna==2.9
importlib-metadata==1.6.0
ipykernel==5.3.0
ipython==7.15.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.17.0
Jinja2==2.11.2
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.3
jupyter-console==6.1.0
jupyter-core==4.6.3
Keras-Preprocessing==1.1.2
kiwisolver==1.2.0
lxml==4.5.1
Markdown==3.2.2
MarkupSafe==1.1.1
matplotlib==3.2.1
mistune==0.8.4
nbconvert==5.6.1
nbformat==5.0.6
notebook==6.0.3
numpy==1.18.4
oauthlib==3.1.0
opencv-python==4.2.0.34
opt-einsum==3.2.1
packaging==20.4
pandocfilters==1.4.2
parso==0.7.0
pickleshare==0.7.5
Pillow==7.1.2
prometheus-client==0.8.0
prompt-toolkit==3.0.5
protobuf==3.12.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
Pygments==2.6.1
pyparsing==2.4.7
pyrsistent==0.16.0
python-dateutil==2.8.1
pywin32==227
pywinpty==0.5.7
pyzmq==19.0.1
qtconsole==4.7.4
QtPy==1.9.0
requests==2.23.0
requests-oauthlib==1.3.0
rsa==4.0
scipy==1.4.1
Send2Trash==1.5.0
six==1.15.0
tensorboard==2.2.2
tensorboard-plugin-wit==1.6.0.post3
tensorflow-gpu @ file:///E:/DEV/Project_Alot/Image_Detect/tensorflow_gpu-2.2.0-cp37-cp37m-win_amd64.whl
tensorflow-gpu-estimator==2.2.0
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
tornado==6.0.4
traitlets==4.3.3
urllib3==1.25.9
wcwidth==0.2.3
webencodings==0.5.1
Werkzeug==1.0.1
widgetsnbextension==3.5.1
wrapt==1.12.1
zipp==3.1.0

these are the packages installed in my virtual environment.

**Comment by prem48science** [comment]
I just followed the instructions given in the project and I got this error. 
my python version python 3.7.7
absl-py==0.9.0
astunparse==1.6.3
attrs==19.3.0
backcall==0.1.0
bleach==3.1.5
cachetools==4.1.0
certifi==2020.4.5.1
chardet==3.0.4
colorama==0.4.3
cycler==0.10.0
Cython==0.29.19
decorator==4.4.2
defusedxml==0.6.0
entrypoints==0.3
gast==0.3.3
google-auth==1.16.0
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
grpcio==1.29.0
h5py==2.10.0
idna==2.9
importlib-metadata==1.6.0
ipykernel==5.3.0
ipython==7.15.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.17.0
Jinja2==2.11.2
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.3
jupyter-console==6.1.0
jupyter-core==4.6.3
Keras-Preprocessing==1.1.2
kiwisolver==1.2.0
lxml==4.5.1
Markdown==3.2.2
MarkupSafe==1.1.1
matplotlib==3.2.1
mistune==0.8.4
nbconvert==5.6.1
nbformat==5.0.6
notebook==6.0.3
numpy==1.18.4
oauthlib==3.1.0
opencv-python==4.2.0.34
opt-einsum==3.2.1
packaging==20.4
pandocfilters==1.4.2
parso==0.7.0
pickleshare==0.7.5
Pillow==7.1.2
prometheus-client==0.8.0
prompt-toolkit==3.0.5
protobuf==3.12.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
Pygments==2.6.1
pyparsing==2.4.7
pyrsistent==0.16.0
python-dateutil==2.8.1
pywin32==227
pywinpty==0.5.7
pyzmq==19.0.1
qtconsole==4.7.4
QtPy==1.9.0
requests==2.23.0
requests-oauthlib==1.3.0
rsa==4.0
scipy==1.4.1
Send2Trash==1.5.0
six==1.15.0
tensorboard==2.2.2
tensorboard-plugin-wit==1.6.0.post3
tensorflow-gpu @ file:///E:/DEV/Project_Alot/Image_Detect/tensorflow_gpu-2.2.0-cp37-cp37m-win_amd64.whl
tensorflow-gpu-estimator==2.2.0
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
tornado==6.0.4
traitlets==4.3.3
urllib3==1.25.9
wcwidth==0.2.3
webencodings==0.5.1
Werkzeug==1.0.1
widgetsnbextension==3.5.1
wrapt==1.12.1
zipp==3.1.0

these are the packages installed in my virtual environment.

**Comment by pythonlessons** [comment]
You can try install opencv-python==4.1.2
Also, try to run this on Google Colab

**Comment by prem48science** [comment]
yes, I tried again with opencv_python==4.1.2.30 but the error didn't resolve. I will try on google colab and get back.

**Comment by walkvanja** [comment]
@prem48science hi! do you have any updates? I've got the same issue

**Comment by prem48science** [comment]
Hi @walkvanja , I am yet to work on it. but it seems some sort of error with OS. it worked well in ubuntu it seems. [https://github.com/PINTO0309/OpenVINO-YoloV3/issues/15#issue-409708137](url)
i feel it might be some environment error or weights error.

**Comment by pythonlessons** [comment]
So, right now I tried it on Windows 10:
1. Cloned this GitHub repository
2. Downloaded yolov3.weights to model_data
3. ran detection_demo.py both from cmd and from python IDLE
4. everything was just fine...

**Comment by prem48science** [comment]
@pythonlessons I tried it with yolov3 tiny weights (Sorry I didn't mention it before) ... maybe a problem in the usage of the weight.?

**Comment by pythonlessons** [comment]
> @pythonlessons I tried it with yolov3 tiny weights (Sorry I didn't mention it before) ... maybe a problem in the usage of the weight.?

I just tried with yolov3-tiny.weights in a similar way as before:
1. Cloned this GitHub repository
2. Downloaded yolov3-tiny.weights to model_data
3. In configs.py in TRAIN_YOLO_TINY changed from False to True
4. ran detection_demo.py both from cmd and from python IDLE
5. everything was just fine...

**Comment by prem48science** [comment]
@pythonlessons  worked for me too. I didn't set TRAIN_YOLO_TINY to True from False. I just changed Darknet_weights = YOLO_DARKNET_WEIGHTS to Darknet_weights = YOLO_DARKNET_TINY_WEIGHTS
which I guess caused this error. I reset everything and just changed TRAIN_YOLO_TINY to True and it worked. 

thanks for the support. I now close this issue.
