### ISSUE TITLE
setting the maximum number of detected objects

### ISSUE THREAD

**Issue by hadizand** [pythonlessons/TensorFlow-2.x-YOLOv3#60]
I trained a yolo3 model based on my custom dataset. Then, I generated the TFlite model, and it works very well. 
I have the following question:

1. Like other object detection algorithms (Faster-RCCN, SSD families, EfficientDet0-7), can I set the maximum number of detected objects per image? In other words, is there any parameter for setting the maximum number of detected bounding boxes at the image output? 
My dataset contains fingernails of hand, so for a given hand image, I wanna the model gives at most five detected boxes (five fingers).

**Comment by pythonlessons** [comment]
I didn't implement that function, and I do not recommend doing so. Better pick (sort) only 5 boxes with the highest confidence score

**Comment by hadizand** [comment]
Thank you for your reply.
