### ISSUE TITLE
Saving the trained weights as .proto and .txt

### ISSUE THREAD

**Issue by androuino** [pythonlessons/TensorFlow-2.x-YOLOv3#67]
Hi, I was wondering if there is a way I can save the trained weights as like this:

```
# create a Saver object as normal in Python to save your variables
saver = tf.train.Saver(...)
sess = tf.Session()

# Use a saver_def to get the "magic" strings to restore
saver_def = saver.as_saver_def()
print saver_def.filename_tensor_name
print saver_def.restore_op_name

# write out 3 files
saver.save(sess, 'trained_model.sd')
tf.train.write_graph(sess.graph_def, '.', 'trained_model.proto', as_text=False)
tf.train.write_graph(sess.graph_def, '.', 'trained_model.txt', as_text=True)
```

I can't seem to find a class called **_Saver()_** from the TF2 library. Is there another way around that I can achieve the same using this repo?

Thank you in advance.

**Comment by pythonlessons** [comment]
You wrote how to do that in TF1, but my tutorial is TF2. But, I don't know how to do that what you need, you gonna need to find it by yourself.
