### ISSUE TITLE
Train error : index out of bound in dataset.py

### ISSUE THREAD

**Issue by iromzy** [pythonlessons/TensorFlow-2.x-YOLOv3#7]
Hi, thank you for your work and your tutorials. I've got a problem.
I train my own data set, and after the end of the first Epoch, I've got this Error:

epoch: 0 step:   87/89, lr:0.000049, giou_loss:   3.94, conf_loss: 172.47, prob_loss:   7.58, total_loss: 183.99
epoch: 0 step:   88/89, lr:0.000049, giou_loss:   5.02, conf_loss: 173.52, prob_loss:  10.47, total_loss: 189.01
epoch: 0 step:    0/89, lr:0.000050, giou_loss:   3.95, conf_loss: 166.17, prob_loss:   7.58, total_loss: 177.70
epoch: 0 step:    1/89, lr:0.000051, giou_loss:   3.95, conf_loss: 166.40, prob_loss:   9.05, total_loss: 179.41
Traceback (most recent call last):
  File "train.py", line 173, in <module>
    main()
  File "train.py", line 145, in main
    for image_data, target in testset:
  File "/home/bryan/Documents/TensorFlow-2.x-YOLOv3/yolov3/dataset.py", line 97, in __next__
    label_sbbox, label_mbbox, label_lbbox, sbboxes, mbboxes, lbboxes = self.preprocess_true_boxes(bboxes)
  File "/home/bryan/Documents/TensorFlow-2.x-YOLOv3/yolov3/dataset.py", line 220, in preprocess_true_boxes
    label[i][yind, xind, iou_mask, :] = 0
IndexError: index 13 is out of bounds for axis 1 with size 13

I don't think that my test dataset are wrong. Could you help me ?
Thank for reading.

**Comment by pythonlessons** [comment]
Not sure how to help, if the test dataset would be correct, there won't be any error. Check twice, try some experiments, for example, try with few test images

**Comment by jenapss** [comment]
File "/Users/jelaleddin/TensorFlow-2.x-YOLOv3/yolov3/dataset.py", line 220, in preprocess_true_boxes
    label[i][yind, xind, iou_mask, :] = 0
IndexError: index 13 is out of bounds for axis 1 with size 13

**I have the same issue I tried all experiments, they didnt help either. What can the reason of this issue?**

**Comment by pythonlessons** [comment]
Send me a link to download your dataset to reproduce the error.

**Comment by jenapss** [comment]
Sure, I am uploading my dataset to my Google Drive, gonna share the link as it finishes uploading

**Comment by pythonlessons** [comment]
> Sure, I am uploading my dataset to my Google Drive, gonna share the link as it finishes uploading
> Its 3GB dataset

Download new dataset.py file and test it now, should be ok
Tell me if you still receive some kind of errors
