### ISSUE TITLE
Issues when i run detection_custom from pre trained model made in colab

### ISSUE THREAD

**Issue by SigmaReloaded** [pythonlessons/TensorFlow-2.x-YOLOv3#71]
Hi!, i’m following your tutorials to train my own custom datasets in colab, i change into yolov3/configs.py some parameters to train in colab, and its done, i got 3 files:

 
![image](https://user-images.githubusercontent.com/68396278/96343051-68bbae80-105f-11eb-84fb-3ee074d6186b.png)

So, next step that i did is download from GoogleDrive all my folder to run in my local machine.
When i run detection_custom.py i got some error lines:

 
![image](https://user-images.githubusercontent.com/68396278/96343357-7ec96f00-105f-11eb-8bcf-4ac7dc80f2f7.png)

So, i need to change something in config.py to use my custom dataset???

![image](https://user-images.githubusercontent.com/68396278/96343531-8b4dc780-105f-11eb-9dd6-a19bc6f6ce45.png)

![image](https://user-images.githubusercontent.com/68396278/96343585-8ee14e80-105f-11eb-9a96-c40230b23c47.png)

This is also your .py of detection_custom
![image](https://user-images.githubusercontent.com/68396278/96343674-97398980-105f-11eb-8852-f0e0e54b4873.png)

This is also my config.py I’m using this with License plate

![image](https://user-images.githubusercontent.com/68396278/96344139-b7694880-105f-11eb-9cfa-9f1f5b043840.png)

![image](https://user-images.githubusercontent.com/68396278/96344333-c64ffb00-105f-11eb-9372-147a921c77aa.png)

**Comment by pythonlessons** [comment]
In YOLO_CUSTOM_WEIGHTS line you should link your trained model not to write `True`

**Comment by SigmaReloaded** [comment]
That’s all! I did but I too slow, with the same config could I made a yolo tiny?

Saludos cordiales,

Miguel Yance Rodriguez

El 18 oct. 2020, a la(s) 11:58, pythonlessons <notifications@github.com> escribió:

﻿

In YOLO_CUSTOM_WEIGHTS line you should link your trained model not to write True

**Comment by pythonlessons** [comment]
yes, you the same way you can train yolo tiny model.

**Comment by SigmaReloaded** [comment]
What could I do to get more fps in my Raspberry Pi 4? I’m using Yv3 and 4, both tiny, but too slower, almost 1.5-2 FPS

Saludos cordiales,

Miguel Yance Rodriguez

El 20 oct. 2020, a la(s) 02:21, pythonlessons <notifications@github.com> escribió:

﻿

yes, you the same way you can train yolo tiny model.

**Comment by pythonlessons** [comment]
Nothing, get better hardware or do detection somewhere on cloud
