### ISSUE TITLE
cv2.error in dataset.py 

### ISSUE THREAD

**Issue by Haoxuan-Wang** [pythonlessons/TensorFlow-2.x-YOLOv3#73]
When I run to seventy epochs（total 100 epochs） ,Application error ：Opencv (4.2.0) resize.cpp:4048:error :(-215: Assertion failed) inv_scale_x>0 in function 'resize'

**Comment by pythonlessons** [comment]
Not sure, not enough information to tell what's wrong. Check on what image it causes you this error. Always within 17th epoch?

**Comment by Haoxuan-Wang** [comment]
> Not sure, not enough information to tell what's wrong. Check on what image it causes you this error. Always within 17th epoch?

Thank you ， I have another question, if i want to  input 1024*1024 images  ,What changes do I need to make.

**Comment by pythonlessons** [comment]
in configs.py change `YOLO_INPUT_SIZE= 1024`

**Comment by Haoxuan-Wang** [comment]
TRAIN_INPUT_SIZE and TEST_INPUT_SIZE  don't need to be modified ？

**Comment by Haoxuan-Wang** [comment]
I have changed a data set with an image size of 1024. Can I directly input it into the program? Besides YOLO_INPUT_SIZE, what else should I change

**Comment by pythonlessons** [comment]
If you need to train and evaluate the model while training, yes you need to change TRAIN_INPUT_SIZE  and TEST_INPUT_SIZE. You don't need to manually resize images before trying to detect objects. All instructions on how to use and train custom model are written in my tutorials.
