### ISSUE TITLE
How to use multiple GPU to accelerate the training process?

### ISSUE THREAD

**Issue by alextudx** [pythonlessons/TensorFlow-2.x-YOLOv3#77]
Dear Madam or Sir,

I' m just a freshman for the ML and Yolo TF2. Because I could use the High performance computer from my uni, could someone teach me how to use multiple GPU to accelerate the training? I have seen the tf.distribute.Strategy, but I'm also curious, is there some simple way, which may be already finished in this repositories? Thank you very much!

Best Regards
Alex

**Comment by jpcastillo1** [comment]
Did you ever find an easy way to do this?
