### ISSUE TITLE
One channel images training

### ISSUE THREAD

**Issue by alextudx** [pythonlessons/TensorFlow-2.x-YOLOv3#79]
Dear Madam or Sir,

because my training dataset is range-doppler-map, they all could be one channel images. If I want to train the model by one model in order to accelerate the training, is there some simple way by your repo?

And Thank you for sharing the repo.

Best regards
Alex

**Comment by pythonlessons** [comment]
It wasn't implemented for one channel images, this would not work, the simplest way is to convert image to standard 3 channels

**Comment by alextudx** [comment]
> It wasn't implemented for one channel images, this would not work, the simplest way is to convert image to standard 3 channels

Got it and thanks a lot.
