### ISSUE TITLE
print Class name, Confidence score & tracking ID on box side by side 

### ISSUE THREAD

**Issue by Myron1996** [pythonlessons/TensorFlow-2.x-YOLOv3#83]
Hi @pythonlessons . I hope you are doing well. I would really appreciate if you can help me with something. 

Is it possible print **Class name, Confidence score & tracking ID** on box side by side in **_object_tracker.py_**. 

I tried changing several things in following places but for some reason I am unable to do that. 

'''
# draw detection on frame
        image = draw_bbox(original_frame, tracked_bboxes, CLASSES=CLASSES, tracking=True)

        t3 = time.time()
        times.append(t2-t1)
        times_2.append(t3-t1)
        
        times = times[-20:]
        times_2 = times_2[-20:]

        ms = sum(times)/len(times)*1000
        fps = 1000 / ms
        fps2 = 1000 / (sum(times_2)/len(times_2)*1000)
        
        image = cv2.putText(image, "Time: {:.1f} FPS".format(fps), (0, 30), cv2.FONT_HERSHEY_COMPLEX_SMALL, 1, (0, 0, 255), 2)

        # draw original yolo detection
        image = draw_bbox(image, bboxes, CLASSES=CLASSES, show_label=False, rectangle_colors=rectangle_colors, tracking=True)
'''

I would like to print confidence score also beside class name, tracking ID 

 Any advice will be highly appreciated. thank you. 
![Capture](https://user-images.githubusercontent.com/72124771/97678354-97884a80-1a8b-11eb-8a6f-cccab3661258.PNG)

**Comment by pythonlessons** [comment]
Go to draw_bbox function, and use print to debug code

**Comment by Myron1996** [comment]
Thanks for the quick response @pythonlessons . Can you please elaborate a little bit. I am very new the programming in general.

**Comment by pythonlessons** [comment]
Use `print("score_string", score)` instead
