### ISSUE TITLE
UnboundLocalError : local variable 'label_sbbox' referenced before assignment

### ISSUE THREAD

**Issue by Zenhance** [pythonlessons/TensorFlow-2.x-YOLOv3#84]
I have been trying to train a model on Google Colab but when I start training it throws this error. I am training in GPU environment.

`batch_label_sbbox[num, :, :, :, :] = label_sbbox`

This line is in the file yolov3/dataset.py and it is causing the error.
Can you please say what is the problem?

**Comment by tiago-hansen** [comment]
Hi! Were you able to solve this? I am facing the same issue, but with label_mbbox.

**Comment by tiago-hansen** [comment]
![image](https://github.com/pythonlessons/TensorFlow-2.x-YOLOv3/assets/94409497/6af1da40-3513-4af7-80aa-a2d7fe2d3022)
Apparently fixed it by adjusting dataset.py and only assigning those variables when it does not raise the IndexError.
