### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by nandhish35** [pythonlessons/TensorFlow-2.x-YOLOv3#87]
when i try to train the model after few steps of epoch i get the following error . my image size is of 416*416. Thanks in advance
![Screenshot (5)](https://user-images.githubusercontent.com/53225187/98085568-87190b00-1ea3-11eb-912a-9e673ca0e752.png)

**Comment by nandhish35** [comment]
Do anyone know why this error occurs?

**Comment by bedna-KU** [comment]
You have broken dataset. Image do not have bboxes. You need check dataset.

**Comment by nandhish35** [comment]
> You have broken dataset. Image do not have bboxes. You need check dataset.

Thanks .Will check on to that. Also i have a doubt i am runninng this code in my pc with GTX 1050 but i cannot give batch size more than 2. if i give more than 2 allocation error occurs.

**Comment by pythonlessons** [comment]
Yeh, try to find bad image and simply remove it. Probably it's not enough ram on 1050 GPU
