### ISSUE TITLE
Output tensor shapes when converting yolov4 to tflite

### ISSUE THREAD

**Issue by raryanpur** [pythonlessons/TensorFlow-2.x-YOLOv3#89]
Hi,

I'm training Yolov4 using the`YOLOv3_colab_training.ipynb` notebook and custom data, then converting the custom model to tflite format in the notebook as well. Inspecting the converted model using Netron, I'm confused about the shapes of the output tensors. The shape of the input tensor is correct (1, 416, 416, 3), but the three output tensors have the shape (1, 1, 3, 6). I think this is incorrect?

I've trained the model to recognize just one class for testing purposes. My understanding is that the output tensor shapes should be (1, 13, 13, 6), (1, 26, 26, 6), and (1, 52, 52, 6), where the second and third values in each tuple (e.g. 13, 13) represent the grid size, and the fourth value describes a vector of 6 elements - the height, width, centroid, objectness, and class probability of a bounding box for a given grid tile.

To generate the converted model, I've added some code to grid cell 8 ("Create Yolo v3 custom model and load custom trained weights") in `YOLOv3_colab_training.ipynb`. My grid cell 8 looks like the below,

```
yolo = Create_Yolo(input_size=YOLO_INPUT_SIZE, CLASSES=TRAIN_CLASSES)
yolo.load_weights("./checkpoints/yolov3_custom") # use keras weights

# Convert the model
converter = tf.lite.TFLiteConverter.from_keras_model(yolo)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                       tf.lite.OpsSet.SELECT_TF_OPS]

tflite_model = converter.convert()

print("converted model to tflite")

# Save the model.
with open("./checkpoints/yolov4-model.tflite", 'wb') as f:
  f.write(tflite_model)
```

Are the shapes of the output tensors for the converted tflite model incorrect as I suspect?

**Comment by pythonlessons** [comment]
Shouldn't be (1, 1, 3, 6), but actually can't answer why it is like that...
