### ISSUE TITLE
python detection_demo.py

### ISSUE THREAD

**Issue by lihualilee** [pythonlessons/TensorFlow-2.x-YOLOv3#9]
When I execute this statement.python detection_demo.py.Show this error.
![74AK~0_XGVL{ 8)OHCYPT89](https://user-images.githubusercontent.com/64268860/84624574-3add2680-af14-11ea-89df-5f1caddfbc64.png)
Then i changed pred_bbox = YoloV3.predict(image_data) to pred_bbox = YoloV3(image_data).Then the prediction succeeded.
![{VV55H7H`Z`(8GAO0A1%Z`R](https://user-images.githubusercontent.com/64268860/84624812-a921e900-af14-11ea-87cb-b720b76a675a.png)
Why does YoloV3.predict(image_data) fail?

**Comment by jwjuven** [comment]
I think there are some requirements need to be updated in your environment. You can try: pip install -r requirements.txt.

**Comment by Tenesh** [comment]
Yes, you need to install the requirements in txt file. If the issue is resolved please let know so we can close this.

**Comment by lihualilee** [comment]
yes.I have already installed these requirements, but there will still be this error. but I did not have this error when I executed detet_mnist.py
