### ISSUE TITLE
 YOLO_STRIDES

### ISSUE THREAD

**Issue by buianhvu** [pythonlessons/TensorFlow-2.x-YOLOv3#90]
I am trying to understand your code but  in the decode funtion you mention YOLO_STRIDES  = [16, 32, 64] in the config file, and I dont know what it is:     pred_xy = (tf.sigmoid(conv_raw_dxdy) + xy_grid) * STRIDES[i], can you help ?

**Comment by pythonlessons** [comment]
Well, sorry to say, but I forgot a lot of steps from code, from the moment I was writing it, don't have time to get back to it to explain deep steps
