### ISSUE TITLE
mAP of Tiny yolo v3 

### ISSUE THREAD

**Issue by OsamuNomusan** [pythonlessons/TensorFlow-2.x-YOLOv3#92]
First of all, thanks for your useful code.

I tried evaluate_mAP.py for Tiny yolo v3, with coco val2017.
In configs.py, I set TEST_SCORE_THRESHOLD=0.05 and TEST_IOU_THRESHOLD=0.50, following the tutorial.
And also, I changed TRAIN_YOLO_TINY from False to True.

As a result, I got mAP = 15.748%, 15.70 FPS.
This accuracy seems lower than 33.1% shown in your following tutorial.
https://pylessons.com/YOLOv3-TF2-Tiny/

On the other hand, I got a reasonable result of mAP = 57.484%, 12.08 FPS, for Yolo v3.

Do I need more settings for Tiny yolo v3 on evaluate_mAP?

Thanks for your help.

**Comment by pythonlessons** [comment]
Well, actually, I didn't invest a lot of time to tiny yolo while writing this tutorial. There might be some minor mistakes that cause this, actually, this tutorial ate too much time to develop to the point where it is right now. Sad to say, but I don't have time to get back to it...

**Comment by OsamuNomusan** [comment]
Thanks for your response.
I will try to explore it.
Please let me know if you notice anything.

Thanks again.
