### ISSUE TITLE
AssertionError: failed to read all data

### ISSUE THREAD

**Issue by shadabshaikh61** [pythonlessons/TensorFlow-2.x-YOLOv3#95]
I am trying to run the jupyter notebook given in repo.
getting the following error

AssertionError                            Traceback (most recent call last)
<ipython-input-12-14485b4687da> in <module>()
        15 
        16 yolo = Create_Yolo(input_size=YOLO_INPUT_SIZE)
---> 17 load_yolo_weights(yolo, Darknet_weights) # use Darknet weights

/content/gdrive/My Drive/Colab Notebooks/TensorFlow-2.x-YOLOv3-master/TensorFlow-2.x-YOLOv3-master/yolov3/utils.py in load_yolo_weights(model, weights_file)
        72                 conv_layer.set_weights([conv_weights, conv_bias])
        73 
---> 74         assert len(wf.read()) == 0, 'failed to read all data'
        75 
        76 def Load_Yolo_model():

AssertionError: failed to read all data

**Comment by pythonlessons** [comment]
You missed something with configs.py
