### ISSUE TITLE
cannot converted to tflite model

### ISSUE THREAD

**Issue by jeffzhengye** [pythonlessons/TensorFlow-2.x-YOLOv3#96]
I used the following code, but it didn't generate the tflite model. Also didn't get exception or error message, it is so weird. 

Any idea why?

   # measure mAP of trained custom model
    mAP_model.load_weights(save_directory) # use keras weights
    get_mAP(mAP_model, testset, score_threshold=TEST_SCORE_THRESHOLD, iou_threshold=TEST_IOU_THRESHOLD)

    # 转换模型。
    converter = tf.lite.TFLiteConverter.from_keras_model(mAP_model)
    tflite_model = converter.convert()
    # Save the model.
    with open('model.tflite', 'wb') as f:
      f.write(tflite_model)

    interpreter = tf.lite.Interpreter(model_content=tflite_model)
    interpreter.allocate_tensors()

    # 获取输入和输出张量。
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()
    print('input_details', input_details)
    print('output_details', output_details)

    # 使用随机数据作为输入测试 TensorFlow Lite 模型。
    input_shape = input_details[0]['shape']
    input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
    interpreter.set_tensor(input_details[0]['index'], input_data)

    interpreter.invoke()

    # 函数 `get_tensor()` 会返回一份张量的拷贝。
    # 使用 `tensor()` 获取指向张量的指针。
    tflite_results = interpreter.get_tensor(output_details[0]['index'])
    print(tflite_results)

**Comment by pythonlessons** [comment]
First you need to convert to .bp (you can use my script) model, then to tflite

**Comment by jeffzhengye** [comment]
@pythonlessons I did that since it was on the basic tutorial. 
Somehow, I got it fixed as follows (it is kinda weird since It failed me before):

197     converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
198     tag = 'float16'
199     output_name = 'model_float32.tflite'
200     if tag == 'float16':                                                                                                                                            201         converter.optimizations = [tf.lite.Optimize.DEFAULT]
202         converter.target_spec.supported_types = [tf.compat.v1.lite.constants.FLOAT16]
203         converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
204         converter.allow_custom_ops = True
205         output_name = 'model_float16.tflite'
206     elif tag == 'int8':
207         converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
208         converter.optimizations = [tf.lite.Optimize.DEFAULT]
209         converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
210         converter.allow_custom_ops = True
211         # converter.representative_dataset = representative_data_gen
212         output_name = 'model_int8.tflite'

**Comment by jeffzhengye** [comment]
> @pythonlessons I did that since it was on the basic tutorial.
> Somehow, I got it fixed as follows (it is kinda weird since It failed me before):
> 
> 197 converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
> 198 tag = 'float16'
> 199 output_name = 'model_float32.tflite'
> 200 if tag == 'float16': 201 converter.optimizations = [tf.lite.Optimize.DEFAULT]
> 202 converter.target_spec.supported_types = [tf.compat.v1.lite.constants.FLOAT16]
> 203 converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
> 204 converter.allow_custom_ops = True
> 205 output_name = 'model_float16.tflite'
> 206 elif tag == 'int8':
> 207 converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
> 208 converter.optimizations = [tf.lite.Optimize.DEFAULT]
> 209 converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
> 210 converter.allow_custom_ops = True
> 211 # converter.representative_dataset = representative_data_gen
> 212 output_name = 'model_int8.tflite'

I just write it down in case others encounter this problem.
